-- SCRIPT DE SISTEMA DE CONTAS A PAGAR E RECEBER COM FLUXO DE CAIXA
-- DATA: 11/11/2019
-- LOCAL: ITABUNA
-- AUTOR: RONALDO ALVES DA SILVA

 USE DB_CPRF

 IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('DEPARTAMENTOS'))
	CREATE TABLE DEPARTAMENTOS 
	(
	  IdDepartamento INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	  StatusDepartamento TINYINT NOT NULL,
	  NomeDepartamento VARCHAR(50) NOT NULL,
	  SalaNr INT NULL,
	  UsuarioInsert VARCHAR(50) NULL,
	  UsuarioUp VARCHAR(50) NULL,
	  UsuarioDelete VARCHAR(50) NULL,
	  DataInsert VARCHAR(20) NULL,
	  DataUp VARCHAR(20) NULL,
	  DataDelete VARCHAR(20) NULL,
	  HorarioInsert VARCHAR(10) NULL,
	  HorarioUp VARCHAR(10) NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('CARGOS'))
	CREATE TABLE CARGOS
	(
	IdCargo INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	StatusCargo TINYINT  NOT NULL,
	NomeCargo VARCHAR(50) NOT NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	UsuarioDelete VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	DataDelete VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('FORNECEDORES_AC'))
	CREATE TABLE FORNECEDORES_AC
	(
	IdForn INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	ClassFor VARCHAR(20) NULL,
	StatusFor VARCHAR(20) NULL,
	RazaoSocial VARCHAR(250) NULL,	
	NomeFantasia VARCHAR(250) NULL,
	Departamento VARCHAR(200) NULL,
	Cnpj VARCHAR(20) NULL,
	InsEstadual VARCHAR(20) NULL,
	CpfFor VARCHAR(20) NULL,
	NomeContato VARCHAR(300) NULL,
	RgFor VARCHAR(20) NULL,
	Telefone VARCHAR(20) NULL,
	Telefone1 VARCHAR(20) NULL,
	Celular VARCHAR(20) NULL,
	Email VARCHAR(100) NULL,
	Fax VARCHAR(20) NULL,
	Endereco VARCHAR(300) NULL,
	Compl VARCHAR(200) NULL,
	Cep VARCHAR(20) NULL,
	Cidade VARCHAR(200) NULL,
	Estado VARCHAR(2) NULL,
	EnderecoCob VARCHAR(300) NULL,
	ComplCob VARCHAR(200) NULL,
	CepCob VARCHAR(20) NULL,
	CidadeCob VARCHAR(200) NULL,
	EstadoCob VARCHAR(2) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	UsuarioDelete VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	DataDelete VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	Modulo VARCHAR(1) NULL,
	)

	IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('CLIENTES'))
	CREATE TABLE CLIENTES
	(
	IdClie INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	ClassClie VARCHAR(20) NULL,
	StatusClie VARCHAR(20) NULL,
	RazaoSocial VARCHAR(250) NULL,	
	NomeFantasia VARCHAR(250) NULL,
	Departamento VARCHAR(200) NULL,
	Cnpj VARCHAR(20) NULL,
	InsEstadual VARCHAR(20) NULL,
	CpfClie VARCHAR(20) NULL,
	NomeContato VARCHAR(300) NULL,
	RgClie VARCHAR(20) NULL,
	Telefone VARCHAR(20) NULL,
	Telefone1 VARCHAR(20) NULL,
	Celular VARCHAR(20) NULL,
	Email VARCHAR(100) NULL,
	Fax VARCHAR(20) NULL,
	Endereco VARCHAR(300) NULL,
	Compl VARCHAR(200) NULL,
	Cep VARCHAR(20) NULL,
	Cidade VARCHAR(200) NULL,
	Estado VARCHAR(2) NULL,
	EnderecoCob VARCHAR(300) NULL,
	ComplCob VARCHAR(200) NULL,
	CepCob VARCHAR(20) NULL,
	CidadeCob VARCHAR(200) NULL,
	EstadoCob VARCHAR(2) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	UsuarioDelete VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	DataDelete VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	Modulo VARCHAR(1) NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('EMPRESA'))
	CREATE TABLE EMPRESA
	(
	IdEmpresa INT IDENTITY (1,1) PRIMARY KEY NOT NULL,		
	StatusFor VARCHAR(20) NULL,
	DataCadastro DATETIME NULL,
	RazaoSocial VARCHAR(250) NULL,	
	NomeFantasia VARCHAR(250) NULL,	
	Cnpj VARCHAR(20) NULL,
	InsEstadual VARCHAR(20) NULL,	
	NomeContato VARCHAR(300) NULL,
	RgFor VARCHAR(20) NULL,
	Telefone VARCHAR(20) NULL,
	Telefone1 VARCHAR(20) NULL,
	Celular VARCHAR(20) NULL,
	Email VARCHAR(100) NULL,
	Fax VARCHAR(20) NULL,
	Endereco VARCHAR(300) NULL,
	Compl VARCHAR(200) NULL,
	Cep VARCHAR(20) NULL,
	Cidade VARCHAR(200) NULL,
	Estado VARCHAR(2) NULL,
	EnderecoCob VARCHAR(300) NULL,
	ComplCob VARCHAR(200) NULL,
	CepCob VARCHAR(20) NULL,
	CidadeCob VARCHAR(200) NULL,
	EstadoCob VARCHAR(2) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,	
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,	
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,	
	DataAtualizacao DATETIME NULL,
	VersaoAtual VARCHAR(5) NULL,	
	)

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('EMPRESA') AND NAME = 'VersaoAtual')
   ALTER TABLE EMPRESA ADD VersaoAtual VARCHAR(5) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('EMPRESA') AND NAME = 'DataVersao')
   ALTER TABLE EMPRESA ADD DataVersao DATE NULL

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('GRUPOUSUARIOS'))
	CREATE TABLE GRUPOUSUARIOS
	(
	  IdGrupo INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	  StatusGrupo TINYINT NOT NULL,
	  NomeGrupo VARCHAR(50) NOT NULL,
	  UsuarioInsert VARCHAR(50) NULL,
	  UsuarioUp VARCHAR(50) NULL,
	  UsuarioDelete VARCHAR(50) NULL,
	  DataInsert VARCHAR(20) NULL,
	  DataUp VARCHAR(20) NULL,
	  DataDelete VARCHAR(20) NULL,
	  HorarioInsert VARCHAR(10) NULL,
	  HorarioUp VARCHAR(10) NULL,
	)


IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('MODULOS'))
	CREATE TABLE MODULOS
	(
	IdModulo INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	NomeModulo VARCHAR(200) NOT NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('USUARIOS'))
	CREATE TABLE USUARIOS
	(
	IdUsuario INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	StatusUsuario TINYINT NOT NULL,
	DataCadastro DATETIME NULL,
	NomeUsuario VARCHAR(50)NOT NULL,
	LoginUsuario VARCHAR(20) NOT NULL,
	SenhaUsuario VARCHAR(20) NOT NULL,
	ConfirmaSenhaUsuario VARCHAR(300)NOT NULL,
	NomeDepartamento  VARCHAR(20)NOT NULL,
	NomeCargo VARCHAR(300)NOT NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	UsuarioDelete VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	DataDelete VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	)


IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('ACESSOS'))
	CREATE TABLE ACESSOS
	(
	IdAcesso INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	DataLanc DATETIME NULL,
	IdModulo INT FOREIGN KEY REFERENCES MODULOS(IdModulo) NOT NULL,
	IdGrupo INT FOREIGN KEY REFERENCES GRUPOUSUARIOS(IdGrupo) NOT NULL,
	Permissao VARCHAR(10)NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	UsuarioDelete VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	DataDelete VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('USUARIOS_MODULOS'))
	CREATE TABLE USUARIOS_MODULOS
	(
	IdMod INT IDENTITY (1,1) PRIMARY KEY NOT NULL,	
	IdUsuario INT FOREIGN KEY REFERENCES USUARIOS(IdUsuario) NOT NULL,	
	IdGrupo INT FOREIGN KEY REFERENCES GRUPOUSUARIOS(IdGrupo) NOT NULL,
	IdModulo INT FOREIGN KEY REFERENCES MODULOS(IdModulo) NOT NULL,	
	Permissao VARCHAR(3) NOT NULL,			
	)

-- TABELA DE AGENDA DE RECADOS

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('AGENDARECADOS'))
	CREATE TABLE AGENDARECADOS
	(
	IdLanc INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	DataLanc DATETIME NULL,
	Horario VARCHAR(10) NULL,
	StatusAgenda VARCHAR(30) NULL,
	NomeUsuarioLogado VARCHAR(300) NULL,
	IdUsuario INT FOREIGN KEY REFERENCES USUARIOS(IdUsuario) NOT NULL,
	Recados VARCHAR(MAX) NULL,
	MensagemENviada VARCHAR(10) NULL,
	MensagemRecebida VARCHAR(10) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	UsuarioDelete VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	DataDelete VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	)

-- TABELA DE LOG DO SISTEMA

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('LOGSISTEMA'))
	CREATE TABLE LOGSISTEMA
	(
	IdLog INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	DataMov VARCHAR(10) NULL,
	HorarioMov VARCHAR(20) NULL,
	NomeModuloTela VARCHAR(300) NULL,
	IdLancMov INT NULL,
	NomeUsuarioLogado VARCHAR(50) NULL,
	StatusMov VARCHAR(10) NULL, 
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('TELAS'))
	CREATE TABLE TELAS
	(
	IdTelas INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	IdModulo INT FOREIGN KEY REFERENCES MODULOS(IdModulo) NOT NULL,
	NomeTela VARCHAR(600) NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('TELAS_ACESSO'))
	CREATE TABLE TELAS_ACESSO
	(
	IdTela INT IDENTITY (1,1) PRIMARY KEY NOT NULL,	
	IdUsuario INT FOREIGN KEY REFERENCES USUARIOS(IdUsuario) NOT NULL,
	NomeTela VARCHAR(200) NOT NULL,
	NomeModulo VARCHAR(200) NULL,
	Abrir INT NOT NULL,
	Incluir INT NOT NULL,
	Alterar INT NOT NULL,
	Excluir INT NOT NULL,
	Gravar INT NOT NULL,
	Consultar INT NOT NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,	
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,	
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	)

-- TABELA DE PERMISSÕES - PAGAR A TABELA DE ACESSOS SE NÃO FOR UTILIZADA

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('PERMISSOES'))
	CREATE TABLE PERMISSOES
	(
	IdPermissao INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	IdModulo INT FOREIGN KEY REFERENCES MODULOS(IdModulo) NOT NULL,
	IdTela INT FOREIGN KEY REFERENCES TELAS_ACESSO(IdTela) NOT NULL,
	IdGrupo INT FOREIGN KEY REFERENCES GRUPOUSUARIOS(IdGrupo) NOT NULL,
	IdUsuario INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(IdUsuario),
	Abrir VARCHAR(3) NULL,
	Novo VARCHAR(3) NULL,
	Alterar VARCHAR(3) NULL,
	Excluir VARCHAR(3) NULL,
	Gravar VARCHAR(3) NULL,
	Total VARCHAR(3) NULL,
	AcessoGrupo VARCHAR(200) NULL,
	Opcao VARCHAR(3) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	UsuarioDelete VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	DataDelete VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('AGENDARECADOS'))
	CREATE TABLE AGENDARECADOS
	(
	IdLanc INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	DataLanc DATETIME NULL,
	Horario VARCHAR(10) NULL,
	StatusAgenda VARCHAR(30) NULL,
	NomeUsuarioLogado VARCHAR(300) NULL,
	IdUsuario INT FOREIGN KEY REFERENCES USUARIOS(IdUsuario) NOT NULL,
	Recados VARCHAR(MAX) NULL,
	MensagemENviada VARCHAR(10) NULL,
	MensagemRecebida VARCHAR(10) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	UsuarioDelete VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	DataDelete VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('AGENDA_COMPROMISSOS'))
	CREATE TABLE AGENDA_COMPROMISSOS
	(
	IdAgenda INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	StatusAgenda VARCHAR(30) NULL,
	TipoEvento VARCHAR(50) NULL,
	DataAgenda DATETIME NULL,
	Assunto VARCHAR(250) NULL,
	Prioridade VARCHAR(40) NULL,
	Conclusao VARCHAR(40) NULL,
	DataInicio DATE NULL,
	DataTermino DATE NULL,
	HoraInicio VARCHAR(10) NULL,
	HoraTermino VARCHAR(10) NULL,
	DataLembrete DATE NULL,
	HoraLembrete VARCHAR(5) NULL,
	Texto VARCHAR(MAX) NULL,
	UsuarioAgenda VARCHAR(250) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('UNIDADE_PENAL_EMPRESA'))
	CREATE TABLE UNIDADE_PENAL_EMPRESA
	(
	IdUnidEmp INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	IdEmpresa INT FOREIGN KEY REFERENCES EMPRESA(IdEmpresa) NOT NULL,
	DescricaoUnidade VARCHAR(300) NULL,
	Endereco VARCHAR(300) NULL,
	Bairro VARCHAR(100) NULL,
	Cidade VARCHAR(250) NULL,
	Estado VARCHAR(15) NULL,
	Regime VARCHAR(150) NULL,
	CapacidadeMas INT NULL,
	CapacidadeFen INT NULL,
	CapacidadeTotal INT NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,	
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,	
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	)


IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('TIPO_PAGAMENTO'))
	CREATE TABLE TIPO_PAGAMENTO
	(
	IdForma INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	StatusForma VARCHAR(20) NULL,
	DataForma DATETIME NULL,
	DescricaoForma VARCHAR(300) NULL,
	CreditCar INT NULL,
	Visa INT NULL,
	MasterC INT NULL,
	Outros INT NULL,
	Deposito INT NULL,
	Dinheiro INT NULL,
	Cheque INT NULL,
	Boleto INT NULL,
	DebitoC INT NULL,
	Avista INT NULL,
	PagtoCartao INT NULL,
	PagtoDeposito INT NULL,
	PagtoBoleto INT NULL,
	PagtoDebito INT NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,	
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,	
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	--IdEmpresa INT FOREIGN KEY REFERENCES EMPRESA(IdEmpresa) NOT NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('BANCOS_CONTAS'))
   CREATE TABLE BANCOS_CONTAS
    (
	IdBanco INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	StatusBanco VARCHAR(20) NULL,
	DataBanco DATETIME NULL,
	DescricaoBanco VARCHAR(300) NULL,
	Agencia VARCHAR(80) NULL,
	ContaCorrente VARCHAR(100) NULL,
	Operacao VARCHAR(50) NULL,
	Endereco VARCHAR(200) NULL,
	Cidade VARCHAR(100) NULL,
	Estado VARCHAR(60) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,	
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,	
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
--	IdEmpresa INT FOREIGN KEY REFERENCES EMPRESA(IdEmpresa) NOT NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('CENTRO_CUSTO'))
   CREATE TABLE CENTRO_CUSTO
    (
	IdCentro INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	StatusCentro VARCHAR(20) NULL,
	DataCentro DATETIME NULL,
	DescricaoCentro VARCHAR(300) NULL,
	Observacao VARCHAR(MAX) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,	
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,	
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	--IdEmpresa INT FOREIGN KEY REFERENCES EMPRESA(IdEmpresa) NOT NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('TIPO_CONTA'))
   CREATE TABLE TIPO_CONTA
    (
	IdConta INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	StatusConta VARCHAR(20) NULL,
	DataConta DATETIME NULL,
	TipoConta VARCHAR(100) NULL,
	DescricaoConta VARCHAR(300) NULL,
	Observacao VARCHAR(MAX) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,	
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,	
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
--	IdEmpresa INT FOREIGN KEY REFERENCES EMPRESA(IdEmpresa) NOT NULL,
	)


-- TABELA DE MOVIMENTAÇÃO DE CONTRAS A PAGAR E RECEBER.

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('MOVIMENTO_CONTAS_PAGAR_RECEBER'))
	CREATE TABLE MOVIMENTO_CONTAS_PAGAR_RECEBER
	(
	IdMov INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	IdForma INT FOREIGN KEY REFERENCES TIPO_PAGAMENTO(IdForma) NOT NULL,
	IdBanco INT FOREIGN KEY REFERENCES BANCOS_CONTAS(IdBanco) NOT NULL,
	IdCentro INT FOREIGN KEY REFERENCES CENTRO_CUSTO(IdCentro) NOT NULL,
	IdConta INT FOREIGN KEY REFERENCES TIPO_CONTA(IdConta) NOT NULL,
	IdForn INT NOT NULL,
	Operacao VARCHAR(100) NULL,
	DataEmissao DATETIME NULL,
	DataVenc DATETIME NULL,
	Documento VARCHAR(100) NULL,
	ValorDoc REAL NULL,
	Historico VARCHAR(MAX) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,	
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,	
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
--	IdEmpresa INT FOREIGN KEY REFERENCES EMPRESA(IdEmpresa) NOT NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('BAIXA_CONTAS_PAGAR_RECEBER'))
   CREATE TABLE BAIXA_CONTAS_PAGAR_RECEBER
   (
   IdBaixa INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
   IdMov INT FOREIGN KEY REFERENCES MOVIMENTO_CONTAS_PAGAR_RECEBER(IdMov) NOT NULL,
   IdForn INT NOT NULL,
   DataBaixa DATETIME NULL,
   TipoConta VARCHAR(80) NULL,
   DiasAtraso INT NULL,
   JurosDia FLOAT NULL,
   ValorJuros REAL NULL,
   ValorBaixa REAL NOT NULL,
   )

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('SALDO_BANCARIO'))
   CREATE TABLE SALDO_BANCARIO
   (
   IdSaldo INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
   TipoSado VARCHAR(1) NULL,
   DataSaldo DATETIME NULL,
   Doc VARCHAR(80) NULL,
   IdBaixa INT NULL,
   ValorMov REAL NULL,
   SaldoMov REAL NULL,
   )

  -- INSERT INTO GRUPOUSUARIOS(StatusGrupo,NomeGrupo) VALUES(1,'ADMINISTRADOR DO SISTEMA')
  -- INSERT INTO MODULOS(NomeModulo) VALUES('FINANCEIRO')
  -- INSERT INTO USUARIOS(StatusUsuario,DataCadastro,NomeUsuario,NomeDepartamento,NomeCargo,LoginUsuario,SenhaUsuario,ConfirmaSenhaUsuario) VALUES(1,'22/11/2019','ADMINISTRADOR DO SISTEMA','FINANCEIRO','FINANCEIRO','admin',1,1)

  IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('PARAMETROSCRC'))
	CREATE TABLE PARAMETROSCRC
	(
	IdPar INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	QtdDias INT NULL,
	QtdHoras INT NULL,
	UsuarioAutorizado VARCHAR (50) NULL,
	RetornosPortaria VARCHAR(30) NULL,
	EntradasPortaria VARCHAR(3) NULL,
	DataValidade DATETIME NULL,
	LicencaValidade VARCHAR(300) NULL,
	DataAtualizacao DATETIME NULL,
	DocAudiencia VARCHAR(3) NULL,
	DocTrans  VARCHAR(3) NULL,
	DocSaidaTmp  VARCHAR(3) NULL,
	DocLivraPro  VARCHAR(3) NULL,
	ValAudiencia  VARCHAR(3) NULL,
	ValTrans  VARCHAR(3) NULL,
	ValSaidaTmp  VARCHAR(3) NULL,
	ValLivraPro  VARCHAR(3) NULL,
	DocPro VARCHAR(3) NULL,
	DocAlvara VARCHAR(3) NULL,
	ValPro VARCHAR(3) NULL,
	ValAlvara VARCHAR(3) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	UsuarioDelete VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	DataDelete VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	PopulacaoBgp VARCHAR(15) NULL,
	LocacaoBgp VARCHAR(15) NULL,
	TransferenciaBgp VARCHAR(15) NULL,
	PavilhaoCelaBgp VARCHAR(15) NULL,
	PopulacaoBpa VARCHAR(15) NULL,
	LocacaoBpa VARCHAR(15) NULL,
	TransferenciaBpa VARCHAR(15) NULL,
	)

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('PARAMETROSCRC') AND NAME = 'TipoServidor')
   ALTER TABLE PARAMETROSCRC ADD TipoServidor VARCHAR(100) NULL

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('PARAMETROSCRC') AND NAME = 'TipoBancoDados')
   ALTER TABLE PARAMETROSCRC ADD TipoBancoDados VARCHAR(100) NULL

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('USUARIOS_GRUPOS'))
	CREATE TABLE USUARIOS_GRUPOS
	(
	IdUserGroup INT IDENTITY (1,1) PRIMARY KEY NOT NULL,	
	IdUsuario INT FOREIGN KEY REFERENCES USUARIOS(IdUsuario) NOT NULL,	
	IdGrupo INT FOREIGN KEY REFERENCES GRUPOUSUARIOS(IdGrupo) NOT NULL,		
	)
