/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Dao.ConexaoBancoDados;
import Dao.FormaPagamentoDAO;
import Dao.LogSistemaDAO;
import Modelo.FormaPagamento;
import Modelo.LogSistema;
import Util.ModeloTabela;
import static Visao.TelaLoginSenhaCPRF.nameUser;
import static Visao.TelaPrincipal.codigoUserGroup;
import static Visao.TelaPrincipal.codigoGrupo;
import static Visao.TelaPrincipal.nomeGrupo;
import static Visao.TelaPrincipal.codAbrir;
import static Visao.TelaPrincipal.codAlterar;
import static Visao.TelaPrincipal.codConsultar;
import static Visao.TelaPrincipal.codExcluir;
import static Visao.TelaPrincipal.codGravar;
import static Visao.TelaPrincipal.codIncluir;
import static Visao.TelaPrincipal.codUserAcesso;
import static Visao.TelaPrincipal.codigoUser;
import static Visao.TelaPrincipal.jDataSistema;
import static Visao.TelaPrincipal.jHoraSistema;
import static Visao.TelaPrincipal.jPainelPrincipal;
import static Visao.TelaPrincipal.nomeTela;
import static Visao.TelaPrincipal.telaCadastroTiposPagto;
import static Visao.TelaPrincipal.tipoServidor;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author ronal
 */
public class TelaTipoPagamento extends javax.swing.JInternalFrame {

    ConexaoBancoDados conecta = new ConexaoBancoDados();
    FormaPagamento objPagto = new FormaPagamento();
    FormaPagamentoDAO control = new FormaPagamentoDAO();
    LogSistemaDAO controlLog = new LogSistemaDAO();
    LogSistema objLogSys = new LogSistema();
    // Variáveis para gravar o log
    String nomeModuloTela = "Cadastros:Tipo de Pagamento:Manutenção";
    String statusMov;
    String horaMov;
    String dataModFinal;
    //
    int acao, flag;
    String dataInicial, dataFinal, dataAgenda;
    int count = 0;
    int pCARTAO = 0;
    int pCARTAO_VISA = 0;
    int pCARTAO_MASTER = 0;
    int pCARTAO_OUTROS = 0;
    int pDEPOSITO = 0;
    int pDEPOSITO_DINHEIRO = 0;
    int pDEPOSITO_CHEQUE = 0;
    int pBOLETO = 0;
    int pDEBITO_CONTA = 0;
    int pPAGAMENTO_VISTA = 0;
    int pCODIGO_TIPO_PAGAMENTO = 0;

    /**
     * Creates new form TelaTipoPagamento
     */
    public TelaTipoPagamento() {
        initComponents();
        corCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel12 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCodigoPesq = new javax.swing.JTextField();
        jBtCodigoPesq = new javax.swing.JButton();
        jBtDataPesq = new javax.swing.JButton();
        jCheckBoxTodos = new javax.swing.JCheckBox();
        jDataPesqInicial = new com.toedter.calendar.JDateChooser();
        jDataPesqFinal = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaAgendaEventos = new javax.swing.JTable();
        jPanel34 = new javax.swing.JPanel();
        jtotalRegistros = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCodigo = new javax.swing.JTextField();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jDataRegistro = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRBtCartaoCredito = new javax.swing.JRadioButton();
        jRBtOutros = new javax.swing.JRadioButton();
        jRBtMaster = new javax.swing.JRadioButton();
        jRBtVisa = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jRBtDeposito = new javax.swing.JRadioButton();
        jRBtCheque = new javax.swing.JRadioButton();
        jRBtDinheiro = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jRBtBoleto = new javax.swing.JRadioButton();
        btG1 = new javax.swing.JPanel();
        jRBtDebitoConta = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jPrazoPgtoCC = new javax.swing.JFormattedTextField();
        jPanel9 = new javax.swing.JPanel();
        jPrazoPgtoDeposito = new javax.swing.JFormattedTextField();
        jPanel10 = new javax.swing.JPanel();
        jPrazoPgtoBoleto = new javax.swing.JFormattedTextField();
        jPanel11 = new javax.swing.JPanel();
        jPrazoPgtoDebitoConta = new javax.swing.JFormattedTextField();
        jComboBoxDescricaoTipo = new javax.swing.JComboBox<>();
        btG2 = new javax.swing.JPanel();
        jRBtPagamentoVista = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jBtNovo = new javax.swing.JButton();
        jBtAlterar = new javax.swing.JButton();
        jBtExcluir = new javax.swing.JButton();
        jBtSalvar = new javax.swing.JButton();
        jBtCancelar = new javax.swing.JButton();
        jBtSair = new javax.swing.JButton();
        jBtAuditoria = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setTitle("...::: Tipo de Pagamento :::...");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Código:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Data Inicial:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Data Final:");

        jCodigoPesq.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jCodigoPesq.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jBtCodigoPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Lupas_1338_05.gif"))); // NOI18N
        jBtCodigoPesq.setContentAreaFilled(false);
        jBtCodigoPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCodigoPesqActionPerformed(evt);
            }
        });

        jBtDataPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Lupas_1338_05.gif"))); // NOI18N
        jBtDataPesq.setContentAreaFilled(false);
        jBtDataPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDataPesqActionPerformed(evt);
            }
        });

        jCheckBoxTodos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxTodos.setText("Todos");
        jCheckBoxTodos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxTodosItemStateChanged(evt);
            }
        });

        jDataPesqInicial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jDataPesqFinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jDataPesqInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDataPesqFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtDataPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxTodos))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jCodigoPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtCodigoPesq, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBtCodigoPesq)
                    .addComponent(jCodigoPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(6, 6, 6)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCheckBoxTodos)
                    .addComponent(jBtDataPesq)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jDataPesqInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDataPesqFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabelaAgendaEventos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTabelaAgendaEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Data", "Status", "Descrição"
            }
        ));
        jTabelaAgendaEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaAgendaEventosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaAgendaEventos);
        if (jTabelaAgendaEventos.getColumnModel().getColumnCount() > 0) {
            jTabelaAgendaEventos.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTabelaAgendaEventos.getColumnModel().getColumn(1).setPreferredWidth(70);
            jTabelaAgendaEventos.getColumnModel().getColumn(2).setPreferredWidth(70);
            jTabelaAgendaEventos.getColumnModel().getColumn(3).setPreferredWidth(250);
        }

        jPanel34.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        jtotalRegistros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtotalRegistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtotalRegistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
        );

        jPanel33.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        jLabel67.setText("Total de Registros:");

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel67))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel67)
        );

        jPanel35.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        jTabbedPane1.addTab("Listagem", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Status");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Data");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Descrição");

        jCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jCodigo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jCodigo.setEnabled(false);

        jComboBoxStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Ativo", "Inativo" }));
        jComboBoxStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBoxStatus.setEnabled(false);

        jDataRegistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jDataRegistro.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Parcelas");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        buttonGroup1.add(jRBtCartaoCredito);
        jRBtCartaoCredito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRBtCartaoCredito.setText("Cartão Crédito");
        jRBtCartaoCredito.setEnabled(false);
        jRBtCartaoCredito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBtCartaoCreditoItemStateChanged(evt);
            }
        });

        buttonGroup2.add(jRBtOutros);
        jRBtOutros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRBtOutros.setText("Outros");
        jRBtOutros.setEnabled(false);
        jRBtOutros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBtOutrosItemStateChanged(evt);
            }
        });

        buttonGroup2.add(jRBtMaster);
        jRBtMaster.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRBtMaster.setText("Master Card");
        jRBtMaster.setEnabled(false);
        jRBtMaster.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBtMasterItemStateChanged(evt);
            }
        });

        buttonGroup2.add(jRBtVisa);
        jRBtVisa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRBtVisa.setText("Visa");
        jRBtVisa.setEnabled(false);
        jRBtVisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBtVisaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBtCartaoCredito)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jRBtVisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBtMaster)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE)
                .addComponent(jRBtOutros)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBtCartaoCredito)
                    .addComponent(jRBtVisa)
                    .addComponent(jRBtMaster)
                    .addComponent(jRBtOutros))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        buttonGroup1.add(jRBtDeposito);
        jRBtDeposito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRBtDeposito.setText("Depósito");
        jRBtDeposito.setEnabled(false);
        jRBtDeposito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBtDepositoItemStateChanged(evt);
            }
        });

        buttonGroup3.add(jRBtCheque);
        jRBtCheque.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRBtCheque.setText("Cheque");
        jRBtCheque.setEnabled(false);
        jRBtCheque.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBtChequeItemStateChanged(evt);
            }
        });

        buttonGroup3.add(jRBtDinheiro);
        jRBtDinheiro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRBtDinheiro.setText("Dinheiro");
        jRBtDinheiro.setEnabled(false);
        jRBtDinheiro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBtDinheiroItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRBtDeposito)
                .addGap(63, 63, 63)
                .addComponent(jRBtCheque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBtDinheiro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRBtDinheiro)
                    .addComponent(jRBtCheque)
                    .addComponent(jRBtDeposito))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        buttonGroup1.add(jRBtBoleto);
        jRBtBoleto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRBtBoleto.setText("Boleto");
        jRBtBoleto.setEnabled(false);
        jRBtBoleto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBtBoletoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRBtBoleto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRBtBoleto)
                .addContainerGap())
        );

        btG1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        buttonGroup1.add(jRBtDebitoConta);
        jRBtDebitoConta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRBtDebitoConta.setText("Débito em Conta");
        jRBtDebitoConta.setEnabled(false);
        jRBtDebitoConta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBtDebitoContaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout btG1Layout = new javax.swing.GroupLayout(btG1);
        btG1.setLayout(btG1Layout);
        btG1Layout.setHorizontalGroup(
            btG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btG1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRBtDebitoConta)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        btG1Layout.setVerticalGroup(
            btG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btG1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRBtDebitoConta)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        jPrazoPgtoCC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPrazoPgtoCC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPrazoPgtoCC.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPrazoPgtoCC, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPrazoPgtoCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        jPrazoPgtoDeposito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPrazoPgtoDeposito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPrazoPgtoDeposito.setEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPrazoPgtoDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPrazoPgtoDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        jPrazoPgtoBoleto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPrazoPgtoBoleto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPrazoPgtoBoleto.setEnabled(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPrazoPgtoBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPrazoPgtoBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        jPrazoPgtoDebitoConta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPrazoPgtoDebitoConta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPrazoPgtoDebitoConta.setEnabled(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPrazoPgtoDebitoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPrazoPgtoDebitoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        jComboBoxDescricaoTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxDescricaoTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Pagamento com Depósito em Dinheiro", "Pagamento com Cartão de Crédito - Visa", "Pagamento com Cartão de Crédito - MasterCard", "Pagamento com Cartão de Crédito - Outros", "Pagamento com Cartão de Débito", "Pagamento com Depósito em Cheque", "Pagamento com Boleto Bancário", "Pagamento a Vista" }));
        jComboBoxDescricaoTipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBoxDescricaoTipo.setEnabled(false);
        jComboBoxDescricaoTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDescricaoTipoItemStateChanged(evt);
            }
        });

        btG2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        buttonGroup1.add(jRBtPagamentoVista);
        jRBtPagamentoVista.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRBtPagamentoVista.setText("Pagamento a Vista");
        jRBtPagamentoVista.setEnabled(false);
        jRBtPagamentoVista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBtPagamentoVistaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout btG2Layout = new javax.swing.GroupLayout(btG2);
        btG2.setLayout(btG2Layout);
        btG2Layout.setHorizontalGroup(
            btG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btG2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRBtPagamentoVista)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btG2Layout.setVerticalGroup(
            btG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btG2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRBtPagamentoVista)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jDataRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxDescricaoTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel10, jPanel11, jPanel8, jPanel9});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDataRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jComboBoxDescricaoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btG2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btG1, jPanel11});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel10, jPanel6});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel5, jPanel9});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel4, jPanel8});

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        jBtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/page_add.png"))); // NOI18N
        jBtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtNovoActionPerformed(evt);
            }
        });

        jBtAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/8437_16x16.png"))); // NOI18N
        jBtAlterar.setEnabled(false);
        jBtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlterarActionPerformed(evt);
            }
        });

        jBtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/3630_16x16.png"))); // NOI18N
        jBtExcluir.setEnabled(false);
        jBtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirActionPerformed(evt);
            }
        });

        jBtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1294_16x16.png"))); // NOI18N
        jBtSalvar.setEnabled(false);
        jBtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalvarActionPerformed(evt);
            }
        });

        jBtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Button_Close_Icon_16.png"))); // NOI18N
        jBtCancelar.setEnabled(false);
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });

        jBtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Log_Out_Icon_16.png"))); // NOI18N
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });

        jBtAuditoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/book_open.png"))); // NOI18N
        jBtAuditoria.setContentAreaFilled(false);
        jBtAuditoria.setEnabled(false);
        jBtAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAuditoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jBtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jBtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jBtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jBtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jBtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jBtAuditoria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtAlterar, jBtCancelar, jBtExcluir, jBtNovo, jBtSair, jBtSalvar});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jBtAlterar)
                            .addComponent(jBtNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtExcluir)
                            .addComponent(jBtSalvar)
                            .addComponent(jBtCancelar)
                            .addComponent(jBtSair)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtAuditoria)))
                .addGap(5, 5, 5))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtAlterar, jBtCancelar, jBtExcluir, jBtNovo, jBtSair, jBtSalvar});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel3, jPanel7});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jTabbedPane1.addTab("Manutenção", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(300, 30, 527, 380);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtCodigoPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCodigoPesqActionPerformed
        // TODO add your handling code here
        count = 0;
        flag = 1;
        if (jCodigoPesq.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o código para pesquisa.");
        } else {
            preencherTabelaTipoPagto("SELECT * FROM TIPO_PAGAMENTO "
                    + "WHERE IdForma='" + jCodigoPesq.getText() + "'");
        }
    }//GEN-LAST:event_jBtCodigoPesqActionPerformed

    private void jBtDataPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDataPesqActionPerformed
        // TODO add your handling code here:
        flag = 1;
        if (tipoServidor == null || tipoServidor.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "É necessário definir o parâmtero para o sistema operacional utilizado no servidor, (UBUNTU-LINUX ou WINDOWS SERVER).");
        } else if (tipoServidor.equals("Servidor Linux (Ubuntu)/MS-SQL Server")) {
            if (jDataPesqInicial.getDate() == null) {
                JOptionPane.showMessageDialog(rootPane, "Informe a data inicial para pesquisa.");
                jDataPesqInicial.requestFocus();
            } else {
                if (jDataPesqFinal.getDate() == null) {
                    JOptionPane.showMessageDialog(rootPane, "Informe a data final para pesquisa.");
                    jDataPesqFinal.requestFocus();
                } else {
                    if (jDataPesqInicial.getDate().after(jDataPesqFinal.getDate())) {
                        JOptionPane.showMessageDialog(rootPane, "Data Inicial não pode ser maior que data final");
                    } else {
                        SimpleDateFormat formatoAmerica = new SimpleDateFormat("yyyy/MM/dd");
                        dataInicial = formatoAmerica.format(jDataPesqInicial.getDate().getTime());
                        dataFinal = formatoAmerica.format(jDataPesqFinal.getDate().getTime());
                        preencherTabelaTipoPagto("SELECT * FROM TIPO_PAGAMENTO "
                                + "WHERE DataForma BETWEEN'" + dataInicial + "' "
                                + "AND '" + dataFinal + "'");
                    }
                }
            }
        } else if (tipoServidor.equals("Servidor Windows/MS-SQL Server")) {
            if (jDataPesqInicial.getDate() == null) {
                JOptionPane.showMessageDialog(rootPane, "Informe a data inicial para pesquisa.");
                jDataPesqInicial.requestFocus();
            } else {
                if (jDataPesqFinal.getDate() == null) {
                    JOptionPane.showMessageDialog(rootPane, "Informe a data final para pesquisa.");
                    jDataPesqFinal.requestFocus();
                } else {
                    if (jDataPesqInicial.getDate().after(jDataPesqFinal.getDate())) {
                        JOptionPane.showMessageDialog(rootPane, "Data Inicial não pode ser maior que data final");
                    } else {
                        SimpleDateFormat formatoAmerica = new SimpleDateFormat("dd/MM/yyyy");
                        dataInicial = formatoAmerica.format(jDataPesqInicial.getDate().getTime());
                        dataFinal = formatoAmerica.format(jDataPesqFinal.getDate().getTime());
                        preencherTabelaTipoPagto("SELECT * FROM TIPO_PAGAMENTO "
                                + "WHERE DataForma BETWEEN'" + dataInicial + "' "
                                + "AND '" + dataFinal + "'");
                    }
                }
            }
        }
    }//GEN-LAST:event_jBtDataPesqActionPerformed

    private void jCheckBoxTodosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxTodosItemStateChanged
        // TODO add your handling code here:
        count = 0;
        flag = 1;
        if (evt.getStateChange() == evt.SELECTED) {
            this.preencherTabelaTipoPagto("SELECT * FROM TIPO_PAGAMENTO");
        } else {
            jtotalRegistros.setText("");
            limparTabela();
        }
    }//GEN-LAST:event_jCheckBoxTodosItemStateChanged

    private void jTabelaAgendaEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaAgendaEventosMouseClicked
        // TODO add your handling code here:
        flag = 1;
        if (flag == 1) {
            String IdLanc = "" + jTabelaAgendaEventos.getValueAt(jTabelaAgendaEventos.getSelectedRow(), 0);
            jCodigoPesq.setText(IdLanc);
            //
            bloquearBotoes();
            bloquearCampos();
            jBtNovo.setEnabled(true);
            jBtAlterar.setEnabled(true);
            jBtExcluir.setEnabled(true);
            jBtCancelar.setEnabled(true);
            jBtAuditoria.setEnabled(true);
            //
            conecta.abrirConexao();
            try {
                conecta.executaSQL("SELECT * FROM TIPO_PAGAMENTO "
                        + "WHERE IdForma='" + IdLanc + "'");
                conecta.rs.first();
                jCodigo.setText(String.valueOf(conecta.rs.getInt("IdForma")));
                jComboBoxStatus.setSelectedItem(conecta.rs.getString("StatusForma"));
                jDataRegistro.setDate(conecta.rs.getDate("DataForma"));
                jComboBoxDescricaoTipo.setSelectedItem(conecta.rs.getString("DescricaoForma"));
                pCARTAO = conecta.rs.getInt("CreditCar");
                if (pCARTAO == 1) {
                    jRBtCartaoCredito.setSelected(true);
                } else if (pCARTAO == 0) {
                    jRBtCartaoCredito.setSelected(!true);
                }
                pCARTAO_VISA = conecta.rs.getInt("Visa");
                if (pCARTAO_VISA == 1) {
                    jRBtVisa.setSelected(true);
                } else if (pCARTAO_VISA == 0) {
                    jRBtVisa.setSelected(!true);
                }
                pCARTAO_MASTER = conecta.rs.getInt("MasterC");
                if (pCARTAO_MASTER == 1) {
                    jRBtMaster.setSelected(true);
                } else if (pCARTAO_MASTER == 0) {
                    jRBtMaster.setSelected(!true);
                }
                pCARTAO_OUTROS = conecta.rs.getInt("Outros");
                if (pCARTAO_OUTROS == 1) {
                    jRBtOutros.setSelected(true);
                } else if (pCARTAO_OUTROS == 0) {
                    jRBtOutros.setSelected(!true);
                }
                pDEPOSITO = conecta.rs.getInt("Deposito");
                if (pDEPOSITO == 1) {
                    jRBtDeposito.setSelected(true);
                } else if (pDEPOSITO == 0) {
                    jRBtDeposito.setSelected(!true);
                }
                pDEPOSITO_DINHEIRO = conecta.rs.getInt("Dinheiro");
                if (pDEPOSITO_DINHEIRO == 1) {
                    jRBtDinheiro.setSelected(true);
                } else if (pDEPOSITO_DINHEIRO == 0) {
                    jRBtDinheiro.setSelected(!true);
                }
                pDEPOSITO_CHEQUE = conecta.rs.getInt("Cheque");
                if (pDEPOSITO_CHEQUE == 1) {
                    jRBtCheque.setSelected(true);
                } else if (pDEPOSITO_CHEQUE == 0) {
                    jRBtCheque.setSelected(!true);
                }
                pBOLETO = conecta.rs.getInt("Boleto");
                if (pBOLETO == 1) {
                    jRBtBoleto.setSelected(true);
                } else if (pBOLETO == 0) {
                    jRBtBoleto.setSelected(!true);
                }
                pDEBITO_CONTA = conecta.rs.getInt("DebitoC");
                if (pDEBITO_CONTA == 1) {
                    jRBtDebitoConta.setSelected(true);
                } else if (pDEBITO_CONTA == 0) {
                    jRBtDebitoConta.setSelected(!true);
                }
                pPAGAMENTO_VISTA = conecta.rs.getInt("Avista");
                if (pPAGAMENTO_VISTA == 1) {
                    jRBtPagamentoVista.setSelected(true);
                } else if (pPAGAMENTO_VISTA == 0) {
                    jRBtPagamentoVista.setSelected(!true);
                }
                jPrazoPgtoCC.setText(conecta.rs.getString("PagtoCartao"));
                jPrazoPgtoDeposito.setText(conecta.rs.getString("PagtoDeposito"));
                jPrazoPgtoBoleto.setText(conecta.rs.getString("PagtoBoleto"));
                jPrazoPgtoDebitoConta.setText(conecta.rs.getString("PagtoDebito"));
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "ERRO na pesquisa..." + e);
            }
            conecta.desconecta();
        }
    }//GEN-LAST:event_jTabelaAgendaEventosMouseClicked

    private void jBtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtNovoActionPerformed
        // TODO add your handling code here:
        buscarAcessoUsuario(telaCadastroTiposPagto);
        if (codigoUser == codUserAcesso && nomeTela.equals(telaCadastroTiposPagto) && codIncluir == 1 || nameUser.equals("ADMINISTRADOR DO SISTEMA") || nomeGrupo.equals("ADMINISTRADORES")) {
            acao = 1;
            desbloquearCampos();
            limparCampos();
            bloquearBotoes();
            Novo();
            statusMov = "Incluiu";
            horaMov = jHoraSistema.getText();
            dataModFinal = jDataSistema.getText();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuário não tem acesso ao registro.");
        }
    }//GEN-LAST:event_jBtNovoActionPerformed

    private void jBtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlterarActionPerformed
        // TODO add your handling code here:
        buscarAcessoUsuario(telaCadastroTiposPagto);
        if (codigoUser == codUserAcesso && nomeTela.equals(telaCadastroTiposPagto) && codAlterar == 1 || nameUser.equals("ADMINISTRADOR DO SISTEMA") || nomeGrupo.equals("ADMINISTRADORES")) {
            acao = 2;
            desbloquearCampos();
            bloquearBotoes();
            Alterar();
            statusMov = "Alterar";
            horaMov = jHoraSistema.getText();
            dataModFinal = jDataSistema.getText();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuário não tem acesso ao registro.");
        }
    }//GEN-LAST:event_jBtAlterarActionPerformed

    private void jBtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirActionPerformed
        // TODO add your handling code here:
        buscarAcessoUsuario(telaCadastroTiposPagto);
        if (codigoUser == codUserAcesso && nomeTela.equals(telaCadastroTiposPagto) && codExcluir == 1 || nameUser.equals("ADMINISTRADOR DO SISTEMA") || nomeGrupo.equals("ADMINISTRADORES")) {
            statusMov = "Excluiu";
            horaMov = jHoraSistema.getText();
            dataModFinal = jDataSistema.getText();
//            verificarTipoPagamento();
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o interno selecionado?", "Confirmação",
                    JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                objPagto.setIdForma(Integer.valueOf(jCodigo.getText()));
                control.excluirFormaPagamento(objPagto);
                objLog();
                controlLog.incluirLogSistema(objLogSys); // Grava o log da operação
                JOptionPane.showMessageDialog(rootPane, "Registro EXCLUIDO com sucesso !!!");
                bloquearCampos();
                bloquearBotoes();
                limparCampos();
                Excluir();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuário não tem acesso ao registro.");
        }
    }//GEN-LAST:event_jBtExcluirActionPerformed

    private void jBtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalvarActionPerformed
        // TODO add your handling code here:
        buscarAcessoUsuario(telaCadastroTiposPagto);
        if (codigoUser == codUserAcesso && nomeTela.equals(telaCadastroTiposPagto) && codGravar == 1 || nameUser.equals("ADMINISTRADOR DO SISTEMA") || nomeGrupo.equals("ADMINISTRADORES")) {
            if (jComboBoxStatus.getSelectedItem().equals("Selecione...")) {
                JOptionPane.showMessageDialog(rootPane, "Informe o status do registro.");
            } else if (jComboBoxDescricaoTipo.getSelectedItem().equals("Selecione...")) {
                JOptionPane.showMessageDialog(rootPane, "Informe a descrição do tipo de pagamento.");
            } else {
                objPagto.setStatusForma((String) jComboBoxStatus.getSelectedItem());
                objPagto.setDataForma(jDataRegistro.getDate());
                objPagto.setDescricaoForma((String) jComboBoxDescricaoTipo.getSelectedItem());
                if (jRBtCartaoCredito.isSelected()) {
                    pCARTAO = 1;
                } else if (!jRBtCartaoCredito.isSelected()) {
                    pCARTAO = 0;
                }
                objPagto.setCartao(pCARTAO);
                if (jRBtVisa.isSelected()) {
                    pCARTAO_VISA = 1;
                } else if (!jRBtVisa.isSelected()) {
                    pCARTAO_VISA = 0;
                }
                objPagto.setVisa(pCARTAO_VISA);
                if (jRBtMaster.isSelected()) {
                    pCARTAO_MASTER = 1;
                } else if (!jRBtMaster.isSelected()) {
                    pCARTAO_MASTER = 0;
                }
                objPagto.setMaster(pCARTAO_MASTER);
                if (jRBtOutros.isSelected()) {
                    pCARTAO_OUTROS = 1;
                } else if (!jRBtOutros.isSelected()) {
                    pCARTAO_OUTROS = 0;
                }
                objPagto.setOutros(pCARTAO_OUTROS);
                if (jRBtDeposito.isSelected()) {
                    pDEPOSITO = 1;
                } else if (!jRBtDeposito.isSelected()) {
                    pDEPOSITO = 0;
                }
                objPagto.setDeposito(pDEPOSITO);
                if (jRBtDinheiro.isSelected()) {
                    pDEPOSITO_DINHEIRO = 1;
                } else if (!jRBtDinheiro.isSelected()) {
                    pDEPOSITO_DINHEIRO = 0;
                }
                objPagto.setDinheiro(pDEPOSITO_DINHEIRO);
                if (jRBtCheque.isSelected()) {
                    pDEPOSITO_CHEQUE = 1;
                } else if (!jRBtCheque.isSelected()) {
                    pDEPOSITO_CHEQUE = 0;
                }
                objPagto.setCheque(pDEPOSITO_CHEQUE);
                if (jRBtBoleto.isSelected()) {
                    pBOLETO = 1;
                } else if (!jRBtBoleto.isSelected()) {
                    pBOLETO = 0;
                }
                objPagto.setBoleto(pBOLETO);
                if (jRBtDebitoConta.isSelected()) {
                    pDEBITO_CONTA = 1;
                } else if (!jRBtDebitoConta.isSelected()) {
                    pDEBITO_CONTA = 0;
                }
                if (jRBtPagamentoVista.isSelected()) {
                    pPAGAMENTO_VISTA = 1;
                } else if (!jRBtPagamentoVista.isSelected()) {
                    pPAGAMENTO_VISTA = 0;
                }
                objPagto.setAvista(pPAGAMENTO_VISTA);
                objPagto.setDebitoConta(pDEBITO_CONTA);
                objPagto.setFormaPagtoCartao(Integer.valueOf(jPrazoPgtoCC.getText()));
                objPagto.setFormaPagtoDeposito(Integer.valueOf(jPrazoPgtoDeposito.getText()));
                objPagto.setFormaPagtoBoleto(Integer.valueOf(jPrazoPgtoBoleto.getText()));
                objPagto.setFormaPagtoDebito(Integer.valueOf(jPrazoPgtoDebitoConta.getText()));
                if (acao == 1) {
                    objPagto.setUsuarioInsert(nameUser);
                    objPagto.setDataInsert(dataModFinal);
                    objPagto.setHorarioInsert(horaMov);
                    //
                    control.incluirFormaPagamento(objPagto);
                    buscarCodigo();
                    objLog();
                    controlLog.incluirLogSistema(objLogSys); // Grava o log da operação  
                    bloquearCampos();
                    bloquearBotoes();
                    Salvar();
                    JOptionPane.showMessageDialog(rootPane, "Registro gravado com sucesso.");
                }
                if (acao == 2) {
                    objPagto.setUsuarioUp(nameUser);
                    objPagto.setDataUp(dataModFinal);
                    objPagto.setHorarioUp(horaMov);
                    //
                    objPagto.setIdForma(Integer.valueOf(jCodigo.getText()));
                    control.alterarFormaPagamento(objPagto);
                    objLog();
                    controlLog.incluirLogSistema(objLogSys); // Grava o log da operação    
                    bloquearCampos();
                    bloquearBotoes();
                    Salvar();
                    JOptionPane.showMessageDialog(rootPane, "Registro gravado com sucesso.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuário não tem acesso ao registro.");
        }
    }//GEN-LAST:event_jBtSalvarActionPerformed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        // TODO add your handling code here:
        Cancelar();
    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtSairActionPerformed

    private void jBtAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAuditoriaActionPerformed
        // TODO add your handling code here:
        TelaAuditoriaTP objAudTP = new TelaAuditoriaTP();
        jPainelPrincipal.add(objAudTP);
        objAudTP.show();
    }//GEN-LAST:event_jBtAuditoriaActionPerformed

    private void jComboBoxDescricaoTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDescricaoTipoItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == evt.SELECTED && jComboBoxDescricaoTipo.getSelectedItem().equals("Pagamento com Depósito em Dinheiro")) {
            jRBtDeposito.setSelected(true);
            jRBtDinheiro.setSelected(true);
            buttonGroup2.clearSelection();
        } else if (evt.getStateChange() == evt.SELECTED && jComboBoxDescricaoTipo.getSelectedItem().equals("Pagamento com Cartão de Crédito - Visa")) {
            jRBtCartaoCredito.setSelected(true);
            jRBtVisa.setSelected(true);
            buttonGroup3.clearSelection();
        } else if (evt.getStateChange() == evt.SELECTED && jComboBoxDescricaoTipo.getSelectedItem().equals("Pagamento com Cartão de Crédito - MasterCard")) {
            jRBtCartaoCredito.setSelected(true);
            jRBtMaster.setSelected(true);
            buttonGroup3.clearSelection();
        } else if (evt.getStateChange() == evt.SELECTED && jComboBoxDescricaoTipo.getSelectedItem().equals("Pagamento com Cartão de Crédito - Outros")) {
            jRBtCartaoCredito.setSelected(true);
            jRBtOutros.setSelected(true);
            buttonGroup3.clearSelection();
        } else if (evt.getStateChange() == evt.SELECTED && jComboBoxDescricaoTipo.getSelectedItem().equals("Pagamento com Cartão de Débito")) {
            jRBtDebitoConta.setSelected(true);
            buttonGroup2.clearSelection();
            buttonGroup3.clearSelection();
        } else if (evt.getStateChange() == evt.SELECTED && jComboBoxDescricaoTipo.getSelectedItem().equals("Pagamento com Boleto Bancário")) {
            jRBtBoleto.setSelected(true);
            buttonGroup2.clearSelection();
            buttonGroup3.clearSelection();
        } else if (evt.getStateChange() == evt.SELECTED && jComboBoxDescricaoTipo.getSelectedItem().equals("Pagamento com Depósito em Cheque")) {
            jRBtDeposito.setSelected(true);
            jRBtCheque.setSelected(true);
            buttonGroup2.clearSelection();
        } else if (evt.getStateChange() == evt.SELECTED && jComboBoxDescricaoTipo.getSelectedItem().equals("Pagamento a Vista")) {
            jRBtPagamentoVista.setSelected(true);
            buttonGroup2.clearSelection();
            buttonGroup3.clearSelection();
        }
        if (jRBtCartaoCredito.isSelected()) {
            pCARTAO = 1;
        } else if (!jRBtCartaoCredito.isSelected()) {
            pCARTAO = 0;
        }
        objPagto.setCartao(pCARTAO);
        if (jRBtVisa.isSelected()) {
            pCARTAO_VISA = 1;
        } else if (!jRBtVisa.isSelected()) {
            pCARTAO_VISA = 0;
        }
        objPagto.setVisa(pCARTAO_VISA);
        if (jRBtMaster.isSelected()) {
            pCARTAO_MASTER = 1;
        } else if (!jRBtMaster.isSelected()) {
            pCARTAO_MASTER = 0;
        }
        objPagto.setMaster(pCARTAO_MASTER);
        if (jRBtOutros.isSelected()) {
            pCARTAO_OUTROS = 1;
        } else if (!jRBtOutros.isSelected()) {
            pCARTAO_OUTROS = 0;
        }
        objPagto.setOutros(pCARTAO_OUTROS);
        if (jRBtDeposito.isSelected()) {
            pDEPOSITO = 1;
        } else if (!jRBtDeposito.isSelected()) {
            pDEPOSITO = 0;
        }
        objPagto.setDeposito(pDEPOSITO);
        if (jRBtDinheiro.isSelected()) {
            pDEPOSITO_DINHEIRO = 1;
        } else if (!jRBtDinheiro.isSelected()) {
            pDEPOSITO_DINHEIRO = 0;
        }
        objPagto.setDinheiro(pDEPOSITO_DINHEIRO);
        if (jRBtCheque.isSelected()) {
            pDEPOSITO_CHEQUE = 1;
        } else if (!jRBtCheque.isSelected()) {
            pDEPOSITO_CHEQUE = 0;
        }
        objPagto.setCheque(pDEPOSITO_CHEQUE);
        if (jRBtBoleto.isSelected()) {
            pBOLETO = 1;
        } else if (!jRBtBoleto.isSelected()) {
            pBOLETO = 0;
        }
        objPagto.setBoleto(pBOLETO);
        if (jRBtDebitoConta.isSelected()) {
            pDEBITO_CONTA = 1;
        } else if (!jRBtDebitoConta.isSelected()) {
            pDEBITO_CONTA = 0;
        }
        objPagto.setDebitoConta(pDEBITO_CONTA);
        if (jRBtPagamentoVista.isSelected()) {
            pPAGAMENTO_VISTA = 1;
        } else if (!jRBtPagamentoVista.isSelected()) {
            pPAGAMENTO_VISTA = 0;
        }
        objPagto.setAvista(pPAGAMENTO_VISTA);
    }//GEN-LAST:event_jComboBoxDescricaoTipoItemStateChanged

    private void jRBtCartaoCreditoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBtCartaoCreditoItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == evt.SELECTED && jRBtCartaoCredito.isSelected()) {
            jRBtCartaoCredito.setSelected(true);
            buttonGroup3.clearSelection();
        }
    }//GEN-LAST:event_jRBtCartaoCreditoItemStateChanged

    private void jRBtDepositoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBtDepositoItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == evt.SELECTED && jRBtDeposito.isSelected()) {
            jRBtDeposito.setSelected(true);
            buttonGroup2.clearSelection();
        }
    }//GEN-LAST:event_jRBtDepositoItemStateChanged

    private void jRBtBoletoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBtBoletoItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == evt.SELECTED && jRBtBoleto.isSelected()) {
            jRBtBoleto.setSelected(true);
            buttonGroup2.clearSelection();
            buttonGroup3.clearSelection();
        }
    }//GEN-LAST:event_jRBtBoletoItemStateChanged

    private void jRBtDebitoContaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBtDebitoContaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == evt.SELECTED && jRBtDebitoConta.isSelected()) {
            jRBtDebitoConta.setSelected(true);
            buttonGroup2.clearSelection();
            buttonGroup3.clearSelection();
        }
    }//GEN-LAST:event_jRBtDebitoContaItemStateChanged

    private void jRBtPagamentoVistaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBtPagamentoVistaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == evt.SELECTED && jRBtPagamentoVista.isSelected()) {
            jRBtPagamentoVista.setSelected(true);
            buttonGroup2.clearSelection();
            buttonGroup3.clearSelection();
        }
    }//GEN-LAST:event_jRBtPagamentoVistaItemStateChanged

    private void jRBtVisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBtVisaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == evt.SELECTED && jRBtVisa.isSelected()) {
            jRBtVisa.setSelected(true);
            jRBtCartaoCredito.setSelected(true);
            buttonGroup3.clearSelection();
        }
    }//GEN-LAST:event_jRBtVisaItemStateChanged

    private void jRBtMasterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBtMasterItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == evt.SELECTED && jRBtMaster.isSelected()) {
            jRBtMaster.setSelected(true);
            jRBtCartaoCredito.setSelected(true);
            buttonGroup3.clearSelection();
        }
    }//GEN-LAST:event_jRBtMasterItemStateChanged

    private void jRBtOutrosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBtOutrosItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == evt.SELECTED && jRBtOutros.isSelected()) {
            jRBtOutros.setSelected(true);
            jRBtCartaoCredito.setSelected(true);
            buttonGroup3.clearSelection();
        }
    }//GEN-LAST:event_jRBtOutrosItemStateChanged

    private void jRBtChequeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBtChequeItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == evt.SELECTED && jRBtCheque.isSelected()) {
            jRBtCheque.setSelected(true);
            jRBtDeposito.setSelected(true);
            buttonGroup2.clearSelection();
        }
    }//GEN-LAST:event_jRBtChequeItemStateChanged

    private void jRBtDinheiroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBtDinheiroItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == evt.SELECTED && jRBtDinheiro.isSelected()) {
            jRBtDinheiro.setSelected(true);
            jRBtDeposito.setSelected(true);
            buttonGroup2.clearSelection();
        }
    }//GEN-LAST:event_jRBtDinheiroItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btG1;
    private javax.swing.JPanel btG2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jBtAlterar;
    private javax.swing.JButton jBtAuditoria;
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtCodigoPesq;
    private javax.swing.JButton jBtDataPesq;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JButton jBtNovo;
    private javax.swing.JButton jBtSair;
    private javax.swing.JButton jBtSalvar;
    private javax.swing.JCheckBox jCheckBoxTodos;
    public static javax.swing.JTextField jCodigo;
    private javax.swing.JTextField jCodigoPesq;
    private javax.swing.JComboBox<String> jComboBoxDescricaoTipo;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private com.toedter.calendar.JDateChooser jDataPesqFinal;
    private com.toedter.calendar.JDateChooser jDataPesqInicial;
    private com.toedter.calendar.JDateChooser jDataRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JFormattedTextField jPrazoPgtoBoleto;
    private javax.swing.JFormattedTextField jPrazoPgtoCC;
    private javax.swing.JFormattedTextField jPrazoPgtoDebitoConta;
    private javax.swing.JFormattedTextField jPrazoPgtoDeposito;
    private javax.swing.JRadioButton jRBtBoleto;
    private javax.swing.JRadioButton jRBtCartaoCredito;
    private javax.swing.JRadioButton jRBtCheque;
    private javax.swing.JRadioButton jRBtDebitoConta;
    private javax.swing.JRadioButton jRBtDeposito;
    private javax.swing.JRadioButton jRBtDinheiro;
    private javax.swing.JRadioButton jRBtMaster;
    private javax.swing.JRadioButton jRBtOutros;
    private javax.swing.JRadioButton jRBtPagamentoVista;
    private javax.swing.JRadioButton jRBtVisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable jTabelaAgendaEventos;
    public static javax.swing.JLabel jtotalRegistros;
    // End of variables declaration//GEN-END:variables

    public void corCampos() {
        jCodigo.setBackground(Color.white);
        jComboBoxStatus.setBackground(Color.white);
        jDataRegistro.setBackground(Color.white);
        jComboBoxDescricaoTipo.setBackground(Color.white);
        jPrazoPgtoCC.setBackground(Color.white);
        jPrazoPgtoDeposito.setBackground(Color.white);
        jPrazoPgtoBoleto.setBackground(Color.white);
        jPrazoPgtoDebitoConta.setBackground(Color.white);
    }

    public void bloquearCampos() {
        jCodigo.setEnabled(!true);
        jComboBoxStatus.setEnabled(!true);
        jDataRegistro.setEnabled(!true);
        jComboBoxDescricaoTipo.setEnabled(!true);
        jRBtCartaoCredito.setEnabled(!true);
        jRBtVisa.setEnabled(!true);
        jRBtMaster.setEnabled(!true);
        jRBtOutros.setEnabled(!true);
        jRBtDeposito.setEnabled(!true);
        jRBtDinheiro.setEnabled(!true);
        jRBtCheque.setEnabled(!true);
        jRBtBoleto.setEnabled(!true);
        jRBtDebitoConta.setEnabled(!true);
        jRBtPagamentoVista.setEnabled(!true);
        jPrazoPgtoCC.setEnabled(!true);
        jPrazoPgtoDeposito.setEnabled(!true);
        jPrazoPgtoBoleto.setEnabled(!true);
        jPrazoPgtoDebitoConta.setEnabled(!true);
    }

    public void desbloquearCampos() {
        jComboBoxStatus.setEnabled(true);
        jComboBoxDescricaoTipo.setEnabled(true);
        jRBtCartaoCredito.setEnabled(true);
        jRBtVisa.setEnabled(true);
        jRBtMaster.setEnabled(true);
        jRBtOutros.setEnabled(true);
        jRBtDeposito.setEnabled(true);
        jRBtDinheiro.setEnabled(true);
        jRBtCheque.setEnabled(true);
        jRBtBoleto.setEnabled(true);
        jRBtDebitoConta.setEnabled(true);
        jRBtPagamentoVista.setEnabled(true);
        jPrazoPgtoCC.setEnabled(true);
        jPrazoPgtoDeposito.setEnabled(true);
        jPrazoPgtoBoleto.setEnabled(true);
        jPrazoPgtoDebitoConta.setEnabled(true);
    }

    public void limparCampos() {
        jCodigo.setText("");
        jComboBoxStatus.setSelectedItem("Selecione...");
        jDataRegistro.setDate(null);
        jComboBoxDescricaoTipo.setSelectedItem("Selecione...");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        jPrazoPgtoCC.setText("0");
        jPrazoPgtoDeposito.setText("0");
        jPrazoPgtoBoleto.setText("0");
        jPrazoPgtoDebitoConta.setText("0");
    }

    public void bloquearBotoes() {
        jBtNovo.setEnabled(!true);
        jBtAlterar.setEnabled(!true);
        jBtExcluir.setEnabled(!true);
        jBtSalvar.setEnabled(!true);
        jBtCancelar.setEnabled(!true);
        jBtAuditoria.setEnabled(!true);
    }

    public void Novo() {
        jDataRegistro.setCalendar(Calendar.getInstance());
        jBtSalvar.setEnabled(true);
        jBtCancelar.setEnabled(true);
    }

    public void Alterar() {
        jBtSalvar.setEnabled(true);
        jBtCancelar.setEnabled(true);
    }

    public void Excluir() {
        jBtNovo.setEnabled(true);
    }

    public void Salvar() {
        jBtNovo.setEnabled(true);
        jBtAlterar.setEnabled(true);
        jBtExcluir.setEnabled(true);
        jBtAuditoria.setEnabled(true);
    }

    public void Cancelar() {
        if (jCodigo.getText().equals("")) {
            limparCampos();
            bloquearCampos();
            bloquearBotoes();
            jBtNovo.setEnabled(true);
        } else {
            bloquearBotoes();
            bloquearCampos();
            jBtNovo.setEnabled(true);
            jBtAlterar.setEnabled(true);
            jBtExcluir.setEnabled(true);
            jBtSalvar.setEnabled(true);
            jBtAuditoria.setEnabled(true);
        }
    }

    public void buscarCodigo() {
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM TIPO_PAGAMENTO");
            conecta.rs.last();
            jCodigo.setText(conecta.rs.getString("IdForma"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível obter o código do registro.\nERRO: " + e);
        }
        conecta.desconecta();
    }

    public void verificarTipoPagamento() {
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM MOVIMENTO_CONTAS_PAGAR_RECEBER");
            conecta.rs.last();
            pCODIGO_TIPO_PAGAMENTO = conecta.rs.getInt("IdForma");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível obter o código do registro.\nERRO: " + e);
        }
        conecta.desconecta();
    }

    public void preencherTabelaTipoPagto(String sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código ", "Data", "Status", "Descrição"};
        conecta.abrirConexao();
        try {
            conecta.executaSQL(sql);
            conecta.rs.first();
            do {
                count = count + 1;
                // Formatar a data no formato Brasil
                dataAgenda = conecta.rs.getString("DataForma");
                String dia = dataAgenda.substring(8, 10);
                String mes = dataAgenda.substring(5, 7);
                String ano = dataAgenda.substring(0, 4);
                dataAgenda = dia + "/" + mes + "/" + ano;
                jtotalRegistros.setText(Integer.toString(count));
                dados.add(new Object[]{conecta.rs.getInt("IdForma"), dataAgenda, conecta.rs.getString("StatusForma"), conecta.rs.getString("DescricaoForma")});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não existem dados a serem EXIBIDOS!!!");
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaAgendaEventos.setModel(modelo);
        jTabelaAgendaEventos.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTabelaAgendaEventos.getColumnModel().getColumn(0).setResizable(false);
        jTabelaAgendaEventos.getColumnModel().getColumn(1).setPreferredWidth(70);
        jTabelaAgendaEventos.getColumnModel().getColumn(1).setResizable(false);
        jTabelaAgendaEventos.getColumnModel().getColumn(2).setPreferredWidth(70);
        jTabelaAgendaEventos.getColumnModel().getColumn(2).setResizable(false);
        jTabelaAgendaEventos.getColumnModel().getColumn(3).setPreferredWidth(250);
        jTabelaAgendaEventos.getColumnModel().getColumn(3).setResizable(false);
        jTabelaAgendaEventos.setAutoResizeMode(jTabelaAgendaEventos.AUTO_RESIZE_OFF);
        jTabelaAgendaEventos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        alinharCamposTabela();
        conecta.desconecta();
    }

    public void limparTabela() {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código ", "Data", "Status", "Descrição"};
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaAgendaEventos.setModel(modelo);
        jTabelaAgendaEventos.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTabelaAgendaEventos.getColumnModel().getColumn(0).setResizable(false);
        jTabelaAgendaEventos.getColumnModel().getColumn(1).setPreferredWidth(70);
        jTabelaAgendaEventos.getColumnModel().getColumn(1).setResizable(false);
        jTabelaAgendaEventos.getColumnModel().getColumn(2).setPreferredWidth(70);
        jTabelaAgendaEventos.getColumnModel().getColumn(2).setResizable(false);
        jTabelaAgendaEventos.getColumnModel().getColumn(3).setPreferredWidth(250);
        jTabelaAgendaEventos.getColumnModel().getColumn(3).setResizable(false);
        jTabelaAgendaEventos.setAutoResizeMode(jTabelaAgendaEventos.AUTO_RESIZE_OFF);
        jTabelaAgendaEventos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        modelo.getLinhas().clear();
    }

    public void alinharCamposTabela() {
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        //
        jTabelaAgendaEventos.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        jTabelaAgendaEventos.getColumnModel().getColumn(1).setCellRenderer(centralizado);
        jTabelaAgendaEventos.getColumnModel().getColumn(2).setCellRenderer(centralizado);
    }

    public void objLog() {
        objLogSys.setDataMov(dataModFinal);
        objLogSys.setHorarioMov(horaMov);
        objLogSys.setNomeModuloTela(nomeModuloTela);
        objLogSys.setIdLancMov(Integer.valueOf(jCodigo.getText()));
        objLogSys.setNomeUsuarioLogado(nameUser);
        objLogSys.setStatusMov(statusMov);
    }

    public void buscarAcessoUsuario(String nomeTelaAcesso) {
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM USUARIOS "
                    + "WHERE NomeUsuario='" + nameUser + "'");
            conecta.rs.first();
            codigoUser = conecta.rs.getInt("IdUsuario");
        } catch (Exception e) {
        }
        try {
            conecta.executaSQL("SELECT * FROM USUARIOS_GRUPOS "
                    + "INNER JOIN GRUPOUSUARIOS "
                    + "ON USUARIOS_GRUPOS.IdGrupo=GRUPOUSUARIOS.IdGrupo "
                    + "WHERE IdUsuario='" + codigoUser + "'");
            conecta.rs.first();
            codigoUserGroup = conecta.rs.getInt("IdUsuario");
            codigoGrupo = conecta.rs.getInt("IdGrupo");
            nomeGrupo = conecta.rs.getString("NomeGrupo");
        } catch (Exception e) {
        }
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM TELAS_ACESSO "
                    + "WHERE IdUsuario='" + codigoUser + "' "
                    + "AND NomeTela='" + nomeTelaAcesso + "'");
            conecta.rs.first();
            codUserAcesso = conecta.rs.getInt("IdUsuario");
            codAbrir = conecta.rs.getInt("Abrir");
            codIncluir = conecta.rs.getInt("Incluir");
            codAlterar = conecta.rs.getInt("Alterar");
            codExcluir = conecta.rs.getInt("Excluir");
            codGravar = conecta.rs.getInt("Gravar");
            codConsultar = conecta.rs.getInt("Consultar");
            nomeTela = conecta.rs.getString("NomeTela");
        } catch (Exception e) {
        }
        conecta.desconecta();
    }
}
