/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Dao.ConexaoBancoDados;
import Dao.listarClienteBancoSaldoDAO;
import Dao.listarFornecedorSaldoBancoDAO;
import Modelo.Clientes;
import Modelo.Fornecedor;
import Util.ModeloTabela;
import static Visao.TelaPrincipal.tipoServidor;
import java.awt.Color;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author ronal
 */
public class TelaSaldoBancario extends javax.swing.JInternalFrame {

    ConexaoBancoDados conecta = new ConexaoBancoDados();
    //
    String pFAVORECIDO = "";
    float pVALOR_DOCUMENTO_REAL = 0;
    float pVALOR_DOCUMENTO_SALDO = 0;
    String pID_BANCO = "";
    String dataInicial, dataFinal, dataMov;
    int flag = 0;
    int count = 0;
    String pVALOR_DOCUMENTO = "";
    String pVALOR_SALDO_ATUAL = "";

    /**
     * Creates new form TelaSaldoBancario
     */
    public TelaSaldoBancario() {
        initComponents();
        corCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSaldoAtual = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jNomeBanco = new javax.swing.JTextField();
        jAgencia = new javax.swing.JTextField();
        jContaCorrente = new javax.swing.JTextField();
        jBtPesquisar = new javax.swing.JButton();
        jComboBoxCorrentista = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxTipoFornecedorSaldo = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jBtSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaHistoricoBancario = new javax.swing.JTable();
        jPanel34 = new javax.swing.JPanel();
        jtotalRegistros = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDataPesqInicial = new com.toedter.calendar.JDateChooser();
        jDataPesqFinal = new com.toedter.calendar.JDateChooser();
        jBtImpressaoExtrato = new javax.swing.JButton();
        jBtPesquisarMov = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        setClosable(true);
        setIconifiable(true);
        setTitle("...::: Consulta de Saldo Bancário :::...");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Agência");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Conta Corrente");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Correntista");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Saldo Atual R$");

        jSaldoAtual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jSaldoAtual.setForeground(new java.awt.Color(204, 0, 0));
        jSaldoAtual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jSaldoAtual.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        jSaldoAtual.setEnabled(false);
        jSaldoAtual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nome do Banco");

        jNomeBanco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jNomeBanco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jNomeBanco.setEnabled(false);

        jAgencia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jAgencia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jContaCorrente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jContaCorrente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jContaCorrente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jContaCorrente.setEnabled(false);

        jBtPesquisar.setForeground(new java.awt.Color(0, 102, 255));
        jBtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Lupas_1338_05.gif"))); // NOI18N
        jBtPesquisar.setText("Pesquisar");
        jBtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisarActionPerformed(evt);
            }
        });

        jComboBoxCorrentista.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxCorrentista.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBoxCorrentista.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Tipo Favorecido");

        jComboBoxTipoFornecedorSaldo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxTipoFornecedorSaldo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBoxTipoFornecedorSaldo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNomeBanco)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jSaldoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jContaCorrente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAgencia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipoFornecedorSaldo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtPesquisar)
                                    .addComponent(jLabel8))
                                .addGap(0, 128, Short.MAX_VALUE))))
                    .addComponent(jComboBoxCorrentista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBtPesquisar)
                    .addComponent(jAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jContaCorrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipoFornecedorSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNomeBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jComboBoxCorrentista, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSaldoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        jBtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/shutdown-icone-6920-32.png"))); // NOI18N
        jBtSair.setText("Sair");
        jBtSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtSair.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtSair)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jBtSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Dados Bancário", jPanel2);

        jTabelaHistoricoBancario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTabelaHistoricoBancario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data Mov.", "Doc.", "Op.", "Valor R$", "Saldo Atual R$"
            }
        ));
        jScrollPane1.setViewportView(jTabelaHistoricoBancario);
        if (jTabelaHistoricoBancario.getColumnModel().getColumnCount() > 0) {
            jTabelaHistoricoBancario.getColumnModel().getColumn(0).setMinWidth(70);
            jTabelaHistoricoBancario.getColumnModel().getColumn(0).setMaxWidth(70);
            jTabelaHistoricoBancario.getColumnModel().getColumn(1).setMinWidth(80);
            jTabelaHistoricoBancario.getColumnModel().getColumn(1).setMaxWidth(80);
            jTabelaHistoricoBancario.getColumnModel().getColumn(2).setMinWidth(30);
            jTabelaHistoricoBancario.getColumnModel().getColumn(2).setMaxWidth(30);
            jTabelaHistoricoBancario.getColumnModel().getColumn(3).setMinWidth(90);
            jTabelaHistoricoBancario.getColumnModel().getColumn(3).setMaxWidth(90);
            jTabelaHistoricoBancario.getColumnModel().getColumn(4).setMinWidth(100);
            jTabelaHistoricoBancario.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jPanel34.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        jtotalRegistros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtotalRegistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtotalRegistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
        );

        jPanel35.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jPanel33.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        jLabel67.setText("Total de Registros:");

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel67))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel67)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Data Inicial");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Data Final");

        jDataPesqInicial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jDataPesqFinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jBtImpressaoExtrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/240119193225_16.png"))); // NOI18N
        jBtImpressaoExtrato.setToolTipText("Extrato Impressãoo");
        jBtImpressaoExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtImpressaoExtratoActionPerformed(evt);
            }
        });

        jBtPesquisarMov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Lupas_1338_05.gif"))); // NOI18N
        jBtPesquisarMov.setContentAreaFilled(false);
        jBtPesquisarMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisarMovActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDataPesqInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jDataPesqFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtPesquisarMov, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtImpressaoExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBtPesquisarMov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDataPesqFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDataPesqInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtImpressaoExtrato))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        jTabbedPane1.addTab("Histórico", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(360, 30, 382, 382);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisarActionPerformed
        // TODO add your handling code here:
        if (jAgencia.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe uma agência bancária para pesquisa.");
        } else {
            conecta.abrirConexao();
            try {
                conecta.executaSQL("SELECT * FROM BANCOS_CONTAS "
                        + "WHERE BANCOS_CONTAS.Agencia='" + jAgencia.getText() + "'");
                conecta.rs.first();
                pID_BANCO = conecta.rs.getString("IdBanco");
                jAgencia.setText(conecta.rs.getString("Agencia"));
                jContaCorrente.setText(conecta.rs.getString("ContaCorrente"));
                jNomeBanco.setText(conecta.rs.getString("DescricaoBanco"));
                jComboBoxTipoFornecedorSaldo.addItem(conecta.rs.getString("TipoFavorecido"));
                pFAVORECIDO = (conecta.rs.getString("TipoFavorecido"));
                if (pFAVORECIDO.equals("Fornecedor")) {
                    listarFornecedorSaldoBancoDAO listaFornecedorDAO = new listarFornecedorSaldoBancoDAO();
                    try {
                        for (Fornecedor f : listaFornecedorDAO.read()) {
                            jComboBoxCorrentista.addItem(f);
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(TelaBancosContasBancarias.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Fornecedor fornecedor = (Fornecedor) jComboBoxCorrentista.getSelectedItem();
                    fornecedor.getIdForn();
                    fornecedor.getRazaoSocial();
                } else if (pFAVORECIDO.equals("Cliente")) {
                    listarClienteBancoSaldoDAO listaClientesDAO = new listarClienteBancoSaldoDAO();
                    try {
                        for (Clientes c : listaClientesDAO.read()) {
                            jComboBoxCorrentista.addItem(c);
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(TelaBancosContasBancarias.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Clientes clientes = (Clientes) jComboBoxCorrentista.getSelectedItem();
                    clientes.getIdForn();
                    clientes.getRazaoSocial();
                }
                buscarSaldoAtual();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "ERRO na pesquisa..." + e);
            }
        }
    }//GEN-LAST:event_jBtPesquisarActionPerformed

    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtSairActionPerformed

    private void jBtPesquisarMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisarMovActionPerformed
        // TODO add your handling code here:
        flag = 1;
        if (tipoServidor == null || tipoServidor.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "É necessário definir o parâmtero para o sistema operacional utilizado no servidor, (UBUNTU-LINUX ou WINDOWS SERVER).");
        } else if (tipoServidor.equals("Servidor Linux (Ubuntu)/MS-SQL Server")) {
            if (jDataPesqInicial.getDate() == null) {
                JOptionPane.showMessageDialog(rootPane, "Informe a data inicial para pesquisa.");
                jDataPesqInicial.requestFocus();
            } else if (jDataPesqFinal.getDate() == null) {
                JOptionPane.showMessageDialog(rootPane, "Informe a data final para pesquisa.");
                jDataPesqFinal.requestFocus();
            } else if (jDataPesqInicial.getDate().after(jDataPesqFinal.getDate())) {
                JOptionPane.showMessageDialog(rootPane, "Data Inicial não pode ser maior que data final");
            } else {
                SimpleDateFormat formatoAmerica = new SimpleDateFormat("yyyy/MM/dd");
                dataInicial = formatoAmerica.format(jDataPesqInicial.getDate().getTime());
                dataFinal = formatoAmerica.format(jDataPesqFinal.getDate().getTime());
                preencherTabelaContaFornecedor("SELECT * FROM SALDO_BANCARIO "
                        + "INNER JOIN BANCOS_CONTAS "
                        + "ON SALDO_BANCARIO.IdBanco=BANCOS_CONTAS.IdBanco "
                        + "WHERE DataSaldo BETWEEN'" + dataInicial + "' "
                        + "AND '" + dataFinal + "' "
                        + "AND Agencia='" + jAgencia.getText().trim() + "' "
                        + "ORDER BY DataSaldo");
            }
        } else if (tipoServidor.equals("Servidor Windows/MS-SQL Server")) {
            if (jDataPesqInicial.getDate() == null) {
                JOptionPane.showMessageDialog(rootPane, "Informe a data inicial para pesquisa.");
                jDataPesqInicial.requestFocus();
            } else if (jDataPesqFinal.getDate() == null) {
                JOptionPane.showMessageDialog(rootPane, "Informe a data final para pesquisa.");
                jDataPesqFinal.requestFocus();
            } else if (jDataPesqInicial.getDate().after(jDataPesqFinal.getDate())) {
                JOptionPane.showMessageDialog(rootPane, "Data Inicial não pode ser maior que data final");
            } else {
                SimpleDateFormat formatoAmerica = new SimpleDateFormat("dd/MM/yyyy");
                dataInicial = formatoAmerica.format(jDataPesqInicial.getDate().getTime());
                dataFinal = formatoAmerica.format(jDataPesqFinal.getDate().getTime());
                preencherTabelaContaFornecedor("SELECT * FROM SALDO_BANCARIO "
                        + "INNER JOIN BANCOS_CONTAS "
                        + "ON SALDO_BANCARIO.IdBanco=BANCOS_CONTAS.IdBanco "
                        + "WHERE DataSaldo BETWEEN'" + dataInicial + "' "
                        + "AND '" + dataFinal + "' "
                        + "AND Agencia='" + jAgencia.getText().trim() + "' "
                        + "ORDER BY DataSaldo");
            }
        }
    }//GEN-LAST:event_jBtPesquisarMovActionPerformed

    private void jBtImpressaoExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtImpressaoExtratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtImpressaoExtratoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField jAgencia;
    private javax.swing.JButton jBtImpressaoExtrato;
    private javax.swing.JButton jBtPesquisar;
    private javax.swing.JButton jBtPesquisarMov;
    private javax.swing.JButton jBtSair;
    public static javax.swing.JComboBox<Object> jComboBoxCorrentista;
    public static javax.swing.JComboBox<String> jComboBoxTipoFornecedorSaldo;
    private javax.swing.JTextField jContaCorrente;
    private com.toedter.calendar.JDateChooser jDataPesqFinal;
    private com.toedter.calendar.JDateChooser jDataPesqInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jNomeBanco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JFormattedTextField jSaldoAtual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTabelaHistoricoBancario;
    private javax.swing.JTextField jTextField3;
    public static javax.swing.JLabel jtotalRegistros;
    // End of variables declaration//GEN-END:variables

    public void corCampos() {
        jAgencia.setBackground(Color.white);
        jContaCorrente.setBackground(Color.white);
        jComboBoxCorrentista.setBackground(Color.white);
        jNomeBanco.setBackground(Color.white);
        jSaldoAtual.setBackground(Color.white);
    }

    public void buscarSaldoAtual() {
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM SALDO_BANCARIO "
                    + "WHERE SALDO_BANCARIO.IdBanco='" + pID_BANCO + "'");
            conecta.rs.last();
            pVALOR_DOCUMENTO_REAL = conecta.rs.getFloat("SaldoAtual");
            DecimalFormat vd = new DecimalFormat("#,##0.00");
            String vlDoc = vd.format(pVALOR_DOCUMENTO_REAL);
            jSaldoAtual.setText(vlDoc);
        } catch (Exception e) {
        }
        conecta.desconecta();
    }

    public void preencherTabelaContaCliente(String sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Data Mov. ", "Doc.", "Op.", "Valor R$", "Saldo Atual R$"};
        conecta.abrirConexao();
        try {
            conecta.executaSQL(sql);
            conecta.rs.first();
            do {
                count = count + 1;
                // Formatar a data no formato Brasil
                dataMov = conecta.rs.getString("DataSaldo");
                String dia = dataMov.substring(8, 10);
                String mes = dataMov.substring(5, 7);
                String ano = dataMov.substring(0, 4);
                dataMov = dia + "/" + mes + "/" + ano;
                //
                pVALOR_DOCUMENTO_REAL = conecta.rs.getFloat("ValorMov");
                DecimalFormat vd = new DecimalFormat("#,##0.00");
                String vlDoc = vd.format(pVALOR_DOCUMENTO_REAL);
                pVALOR_DOCUMENTO = vlDoc;
                //
                pVALOR_DOCUMENTO_SALDO = conecta.rs.getFloat("SaldoAtual");
                DecimalFormat vsa = new DecimalFormat("#,##0.00");
                String vlDocSa = vsa.format(pVALOR_DOCUMENTO_SALDO);
                pVALOR_SALDO_ATUAL = vlDocSa;
                //
                jtotalRegistros.setText(Integer.toString(count));
                dados.add(new Object[]{dataMov, conecta.rs.getString("Doc"), conecta.rs.getString("TipoOperacao"), pVALOR_DOCUMENTO, pVALOR_SALDO_ATUAL});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não existem dados a serem EXIBIDOS!!!");
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaHistoricoBancario.setModel(modelo);
        jTabelaHistoricoBancario.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTabelaHistoricoBancario.getColumnModel().getColumn(0).setResizable(false);
        jTabelaHistoricoBancario.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTabelaHistoricoBancario.getColumnModel().getColumn(1).setResizable(false);
//        jTabelaHistoricoBancario.getColumnModel().getColumn(2).setPreferredWidth(250);
//        jTabelaHistoricoBancario.getColumnModel().getColumn(2).setResizable(false);
        jTabelaHistoricoBancario.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTabelaHistoricoBancario.getColumnModel().getColumn(2).setResizable(false);
        jTabelaHistoricoBancario.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTabelaHistoricoBancario.getColumnModel().getColumn(3).setResizable(false);
        jTabelaHistoricoBancario.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTabelaHistoricoBancario.getColumnModel().getColumn(4).setResizable(false);
        jTabelaHistoricoBancario.setAutoResizeMode(jTabelaHistoricoBancario.AUTO_RESIZE_OFF);
        jTabelaHistoricoBancario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        alinharCamposTabela();
        conecta.desconecta();
    }

    public void preencherTabelaContaFornecedor(String sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Data Mov. ", "Doc.", "Op.", "Valor R$", "Saldo Atual R$"};
        conecta.abrirConexao();
        try {
            conecta.executaSQL(sql);
            conecta.rs.first();
            do {
                count = count + 1;
                // Formatar a data no formato Brasil
                dataMov = conecta.rs.getString("DataSaldo");
                String dia = dataMov.substring(8, 10);
                String mes = dataMov.substring(5, 7);
                String ano = dataMov.substring(0, 4);
                dataMov = dia + "/" + mes + "/" + ano;
                //
                pVALOR_DOCUMENTO_REAL = conecta.rs.getFloat("ValorMov");
                DecimalFormat vd = new DecimalFormat("#,##0.00");
                String vlDoc = vd.format(pVALOR_DOCUMENTO_REAL);
                pVALOR_DOCUMENTO = vlDoc;
                //
                pVALOR_DOCUMENTO_SALDO = conecta.rs.getFloat("SaldoAtual");
                DecimalFormat vsa = new DecimalFormat("#,##0.00");
                String vlDocSa = vsa.format(pVALOR_DOCUMENTO_SALDO);
                pVALOR_SALDO_ATUAL = vlDocSa;
                //
                jtotalRegistros.setText(Integer.toString(count));
                dados.add(new Object[]{dataMov, conecta.rs.getString("Doc"), conecta.rs.getString("TipoOperacao"), pVALOR_DOCUMENTO, pVALOR_SALDO_ATUAL});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não existem dados a serem EXIBIDOS!!!");
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaHistoricoBancario.setModel(modelo);
        jTabelaHistoricoBancario.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTabelaHistoricoBancario.getColumnModel().getColumn(0).setResizable(false);
        jTabelaHistoricoBancario.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTabelaHistoricoBancario.getColumnModel().getColumn(1).setResizable(false);
//        jTabelaHistoricoBancario.getColumnModel().getColumn(2).setPreferredWidth(250);
//        jTabelaHistoricoBancario.getColumnModel().getColumn(2).setResizable(false);
        jTabelaHistoricoBancario.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTabelaHistoricoBancario.getColumnModel().getColumn(2).setResizable(false);
        jTabelaHistoricoBancario.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTabelaHistoricoBancario.getColumnModel().getColumn(3).setResizable(false);
        jTabelaHistoricoBancario.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTabelaHistoricoBancario.getColumnModel().getColumn(4).setResizable(false);
        jTabelaHistoricoBancario.setAutoResizeMode(jTabelaHistoricoBancario.AUTO_RESIZE_OFF);
        jTabelaHistoricoBancario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        alinharCamposTabela();
        conecta.desconecta();
    }

    public void limparTabela() {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Data Mov. ", "Doc.", "Op.", "Valor R$", "Saldo Atual R$"};
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaHistoricoBancario.setModel(modelo);
        jTabelaHistoricoBancario.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTabelaHistoricoBancario.getColumnModel().getColumn(0).setResizable(false);
        jTabelaHistoricoBancario.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTabelaHistoricoBancario.getColumnModel().getColumn(1).setResizable(false);
//        jTabelaHistoricoBancario.getColumnModel().getColumn(2).setPreferredWidth(250);
//        jTabelaHistoricoBancario.getColumnModel().getColumn(2).setResizable(false);
        jTabelaHistoricoBancario.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTabelaHistoricoBancario.getColumnModel().getColumn(2).setResizable(false);
        jTabelaHistoricoBancario.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTabelaHistoricoBancario.getColumnModel().getColumn(3).setResizable(false);
        jTabelaHistoricoBancario.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTabelaHistoricoBancario.getColumnModel().getColumn(4).setResizable(false);
        jTabelaHistoricoBancario.setAutoResizeMode(jTabelaHistoricoBancario.AUTO_RESIZE_OFF);
        jTabelaHistoricoBancario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        modelo.getLinhas().clear();
    }

    public void alinharCamposTabela() {
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        //
        jTabelaHistoricoBancario.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        jTabelaHistoricoBancario.getColumnModel().getColumn(1).setCellRenderer(centralizado);
        jTabelaHistoricoBancario.getColumnModel().getColumn(2).setCellRenderer(centralizado);
        jTabelaHistoricoBancario.getColumnModel().getColumn(3).setCellRenderer(direita);
        jTabelaHistoricoBancario.getColumnModel().getColumn(4).setCellRenderer(direita);
    }
}
