/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Dao.BaixaDAO;
import Dao.BancosContasBancariasDAO;
import Dao.ClientesDAO;
import Dao.ConexaoBancoDados;
import Dao.FornecedoresDAO;
import Modelo.BaixaCPR;
import Modelo.BancosContas;
import Modelo.CentroCusto;
import Modelo.Clientes;
import Modelo.EmpresaUnidade;
import Modelo.FormaPagamento;
import Modelo.Fornecedor;
import Modelo.TipoConta;
import static Visao.TelaMovimentacaoContasPR.jCodigo;
import static Visao.TelaMovimentacaoContasPR.jComboBoxBanco;
import static Visao.TelaMovimentacaoContasPR.jComboBoxCentroCusto;
import static Visao.TelaMovimentacaoContasPR.jComboBoxContaCorrente;
import static Visao.TelaMovimentacaoContasPR.jComboBoxFornecedorCliente;
import static Visao.TelaMovimentacaoContasPR.jComboBoxOperacao;
import static Visao.TelaMovimentacaoContasPR.jComboBoxTipoDespesa;
import static Visao.TelaMovimentacaoContasPR.jComboBoxTipoPagamento;
import static Visao.TelaMovimentacaoContasPR.jDataEmissao;
import static Visao.TelaMovimentacaoContasPR.jDataVencimento;
import static Visao.TelaMovimentacaoContasPR.jNumeroDocumento;
import static Visao.TelaMovimentacaoContasPR.jValorDocumento;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Currency;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ronal
 */
public class TelaBaixaCPR extends javax.swing.JDialog {

    ConexaoBancoDados conecta = new ConexaoBancoDados();
    TipoConta objTipoConta = new TipoConta();
    FormaPagamento objPagto = new FormaPagamento();
    Fornecedor objForn = new Fornecedor();
    Clientes objClie = new Clientes();
    CentroCusto objCentro = new CentroCusto();
    BancosContas objBanco = new BancosContas();
    EmpresaUnidade objEmpUni = new EmpresaUnidade();
    BaixaCPR objBaixa = new BaixaCPR();
    BaixaDAO control = new BaixaDAO();
    //
    float pVALOR_JUROS;
    float pVALOR_TOTAL_OPERACAO;
    float pVALOR_TOTAL_PARCIAL;
    float pVALOR_DIARIO;
    String pCODIGO_MOV_BAIXA = "";
    String pTIPO_OPERACAO_PAGAR = "D";
    String pTIPO_OPERACAO_RECEBER = "C";
    float pVALOR_DOCUMENTO_REAL;
    float pVALOR_BAIXA;
    float pJUROS_PESQUISA;
    float pVALOR_JUROS_PESQUISA;
    float pSALDO_BANCARIO;
    float pSALDO_ATUAL;
    String pCONTA_BAIXADA = "Sim";
    String pCODIGO_BANCO = "";
    /**
     * Creates new form TelaBaixaCPR
     */
    public static TelaMovimentacaoContasPR pMOVI_CONTAS_PR;

    public TelaBaixaCPR(TelaMovimentacaoContasPR parent, boolean modal) {
        this.pMOVI_CONTAS_PR = parent;
        this.setModal(modal);
        setLocationRelativeTo(pMOVI_CONTAS_PR);
        initComponents();
        corCampos();
        buscarOperacao();
        verificarBaixa();
        if (jCodigo.getText().equals(pCODIGO_MOV_BAIXA)) {
            mostrarBaixa();
            Confirmar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBoxOperacaoBaixa = new javax.swing.JComboBox<>();
        jDataEmissaoBaixa = new com.toedter.calendar.JDateChooser();
        jDataVencimentoOperacao = new com.toedter.calendar.JDateChooser();
        jDataOperacao = new com.toedter.calendar.JDateChooser();
        jDocumentoBaixa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jValorPRBaixa = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jValorOperacao = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCodigoOperacao = new javax.swing.JTextField();
        jTipoDespesaBaixa = new javax.swing.JComboBox<>();
        jCentroCustoBaixa = new javax.swing.JComboBox<>();
        jClienteFornecedorBaixa = new javax.swing.JComboBox<>();
        jTipoPagamentoBaixa = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jDiasAtraso = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jJurosDia = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jValorJuros = new javax.swing.JFormattedTextField();
        jBtCalcular = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxContaBanco = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxAgenciaBaixa = new javax.swing.JComboBox<>();
        jBtImprimir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jBtConfirmar = new javax.swing.JButton();
        jBtSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("...::: Baixa de Contas a Pagar/Receber :::...");

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)));

        jComboBoxOperacaoBaixa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxOperacaoBaixa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Pagar", "Receber" }));
        jComboBoxOperacaoBaixa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBoxOperacaoBaixa.setEnabled(false);

        jDataEmissaoBaixa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jDataEmissaoBaixa.setEnabled(false);

        jDataVencimentoOperacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jDataVencimentoOperacao.setEnabled(false);

        jDataOperacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jDataOperacao.setEnabled(false);

        jDocumentoBaixa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jDocumentoBaixa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jDocumentoBaixa.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("OPERAÇÃO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nº DOC");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("DATA EMISSÃO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("DATA VENC.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("DT.OPERAÇÃO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("TIPO DESPESA");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("PLANO DE CONTA");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("CLIENTE/FORNECEDOR");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("VALOR");

        jValorPRBaixa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jValorPRBaixa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jValorPRBaixa.setText("0");
        jValorPRBaixa.setEnabled(false);
        jValorPRBaixa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("VL. OPERAÇÃO");

        jValorOperacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jValorOperacao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jValorOperacao.setText("0");
        jValorOperacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("TIPO PAGAMENTO");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Nº DOC");

        jCodigoOperacao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jCodigoOperacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jCodigoOperacao.setEnabled(false);

        jTipoDespesaBaixa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTipoDespesaBaixa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTipoDespesaBaixa.setEnabled(false);

        jCentroCustoBaixa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCentroCustoBaixa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jCentroCustoBaixa.setEnabled(false);

        jClienteFornecedorBaixa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jClienteFornecedorBaixa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jClienteFornecedorBaixa.setEnabled(false);

        jTipoPagamentoBaixa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTipoPagamentoBaixa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTipoPagamentoBaixa.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jClienteFornecedorBaixa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxOperacaoBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDataEmissaoBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDocumentoBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDataVencimentoOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jTipoDespesaBaixa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCentroCustoBaixa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel5)
                                .addComponent(jDataOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jValorPRBaixa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jValorOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jTipoPagamentoBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jCodigoOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCodigoOperacao, jValorOperacao, jValorPRBaixa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBoxOperacaoBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDataEmissaoBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDocumentoBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDataVencimentoOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDataOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jValorPRBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTipoDespesaBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jValorOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCentroCustoBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jClienteFornecedorBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCodigoOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTipoPagamentoBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("DIAS ATRASO");

        jDiasAtraso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jDiasAtraso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jDiasAtraso.setText("0");
        jDiasAtraso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("JUROS P/DIA");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("VALOR JUROS");

        jJurosDia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jJurosDia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jJurosDia.setText("0");
        jJurosDia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("%");

        jValorJuros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jValorJuros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jValorJuros.setText("0");
        jValorJuros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jBtCalcular.setForeground(new java.awt.Color(0, 0, 204));
        jBtCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calculator.png"))); // NOI18N
        jBtCalcular.setText("Calcular");
        jBtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDiasAtraso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jJurosDia, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jValorJuros)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBtCalcular)
                    .addComponent(jValorJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jJurosDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDiasAtraso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("LANÇAR NA CONTA DO BANCO");

        jComboBoxContaBanco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxContaBanco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBoxContaBanco.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("AGÊNCIA");

        jComboBoxAgenciaBaixa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxAgenciaBaixa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBoxAgenciaBaixa.setEnabled(false);

        jBtImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/240119193225_16.png"))); // NOI18N
        jBtImprimir.setText("Imprimir");
        jBtImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jComboBoxAgenciaBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxContaBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBtImprimir)
                    .addComponent(jComboBoxContaBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAgenciaBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("BAIXA");

        jBtConfirmar.setForeground(new java.awt.Color(0, 102, 0));
        jBtConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/40_16x16.png"))); // NOI18N
        jBtConfirmar.setText("Confirmar");
        jBtConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtConfirmar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtConfirmarActionPerformed(evt);
            }
        });

        jBtSair.setForeground(new java.awt.Color(204, 0, 0));
        jBtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/shutdown-icone-6920-16.png"))); // NOI18N
        jBtSair.setText("Sair");
        jBtSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtSair)
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtConfirmar, jBtSair});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtSair)
                            .addComponent(jBtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtConfirmar, jBtSair});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtConfirmarActionPerformed
        // TODO add your handling code here:
        //VERIFICAR SE REGISTRO JÁ FOI DADO BAIXA.
        //NÃO PERMITE QUE SEJA DADO BAIXA DUAS VEZES PARA O MESMO REGISTRO.
        verificarBaixa();
        if (jCodigo.getText().equals(pCODIGO_MOV_BAIXA)) {
            JOptionPane.showMessageDialog(rootPane, "Esse registro já foi baixado.");
        } else {
            pesquisarRegistros();
            if (jValorOperacao.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Informe o valor da operação.");
            } else if (jDiasAtraso.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "O campo dias de atraso não pode ser em branco.");
            } else if (jJurosDia.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "O campo juros por dia não pode ser em branco.");
            } else if (jValorJuros.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "O campo valor dos juros não pode ser em branco.");
            } else {
                DecimalFormat VALOR_REAL = new DecimalFormat("###,##00.0");
                VALOR_REAL.setCurrency(Currency.getInstance(new Locale("pt", "BR")));
                objBaixa.setOperacaoBaixa((String) jComboBoxOperacaoBaixa.getSelectedItem());
                objBaixa.setIdMov(Integer.valueOf(jCodigo.getText()));
                objBaixa.setDataOperacao(jDataOperacao.getDate());
                objBaixa.setDocumentoBaixa(jDocumentoBaixa.getText());
                objBaixa.setDiasAtraso(Integer.valueOf(jDiasAtraso.getText()));
                objBaixa.setAgencia(pCODIGO_MOV_BAIXA);
                try {
                    objBaixa.setValorOperacao(VALOR_REAL.parse(jValorOperacao.getText()).floatValue());
                    objBaixa.setJurosDias(VALOR_REAL.parse(jJurosDia.getText()).floatValue());
                    objBaixa.setValorJurosDias(VALOR_REAL.parse(jValorJuros.getText()).floatValue());
                    objBaixa.setValorSaldo(VALOR_REAL.parse(jValorOperacao.getText()).floatValue());
                } catch (ParseException ex) {
                    Logger.getLogger(TelaMovimentacaoContasPR.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (jComboBoxOperacaoBaixa.getSelectedItem().equals("Pagar")) {
                    FornecedoresDAO dao = new FornecedoresDAO();
                    try {
                        for (Fornecedor p : dao.read()) {
                            jComboBoxFornecedorCliente.addItem(p);
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(TelaMovimentacaoContasPR.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Fornecedor fornecedor = (Fornecedor) jComboBoxFornecedorCliente.getSelectedItem();
                    fornecedor.getIdForn();
                    fornecedor.getRazaoSocial();
                    objBaixa.setIdForn(fornecedor.getIdForn());
                } else if (jComboBoxOperacaoBaixa.getSelectedItem().equals("Receber")) {
                    ClientesDAO dao = new ClientesDAO();
                    try {
                        for (Clientes c : dao.read()) {
                            jComboBoxFornecedorCliente.addItem(c);
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(TelaMovimentacaoContasPR.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Clientes cliente = (Clientes) jComboBoxFornecedorCliente.getSelectedItem();
                    cliente.getIdForn();
                    cliente.getRazaoSocial();
                    objBaixa.setIdForn(cliente.getIdForn());
                }
                BancosContasBancariasDAO daoBanc = new BancosContasBancariasDAO();
                try {
                    for (BancosContas b : daoBanc.read()) {
                        jComboBoxAgenciaBaixa.addItem(b);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(TelaMovimentacaoContasPR.class.getName()).log(Level.SEVERE, null, ex);
                }
                BancosContas banco = (BancosContas) jComboBoxAgenciaBaixa.getSelectedItem();
                banco.getIdBanco();
                objBaixa.setIdBanco(banco.getIdBanco());
                //INCLUIR REGISTRO DE BAIXA DE CONTAS A PAGAR E A RECEBER
                control.incluirBaixaCPR(objBaixa);
                buscarCodigo();
                //PESQUISAR SALDO BANCÁRIO
                pesquisaSaldoBancario();
                // INCLUIR SALDO NA TABELA DE SALDO_BANCARIO
                if (jComboBoxOperacao.getSelectedItem().equals("Pagar")) {
                    objBaixa.setIdBaixa(Integer.valueOf(jCodigoOperacao.getText()));
                    objBaixa.setTipoOperacao(pTIPO_OPERACAO_PAGAR);
                    pSALDO_ATUAL = pSALDO_BANCARIO - objBaixa.getValorOperacao();
                    objBaixa.setValorSaldo(pSALDO_ATUAL);
                    control.incluirSaldoCPR(objBaixa);
                } else if (jComboBoxOperacao.getSelectedItem().equals("Receber")) {
                    objBaixa.setIdBaixa(Integer.valueOf(jCodigoOperacao.getText()));
                    objBaixa.setTipoOperacao(pTIPO_OPERACAO_RECEBER);
                    pSALDO_ATUAL = pSALDO_BANCARIO + objBaixa.getValorOperacao();
                    objBaixa.setValorSaldo(pSALDO_ATUAL);
                    control.incluirSaldoCPR(objBaixa);
                }
                // ATUALIZAR A MOVIMENTAÇÃO DE CONTAS A PAGAR E RECEBER INFORMANDO A BAIXA
                // PARA NÃO TRAZER AS CONTAS PAGAS.
                objBaixa.setIdMov(Integer.valueOf(jCodigo.getText()));
                objBaixa.setContaBaixada(pCONTA_BAIXADA);
                control.atualizarMovimentoCPR(objBaixa);
                Confirmar();
                JOptionPane.showMessageDialog(rootPane, "Registro gravado com sucesso.");
            }
        }
    }//GEN-LAST:event_jBtConfirmarActionPerformed

    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtSairActionPerformed

    private void jBtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCalcularActionPerformed
        // TODO add your handling code here:
        DecimalFormat VALOR_REAL = new DecimalFormat("###,##00.0");
        VALOR_REAL.setCurrency(Currency.getInstance(new Locale("pt", "BR")));
        try {
            objBaixa.setValorPRBaixa(VALOR_REAL.parse(jValorDocumento.getText()).floatValue());
            objBaixa.setJurosDias(VALOR_REAL.parse(jJurosDia.getText()).floatValue());
            objBaixa.setValorJurosDias(VALOR_REAL.parse(jValorJuros.getText()).floatValue());
        } catch (ParseException ex) {
            Logger.getLogger(TelaBaixaCPR.class.getName()).log(Level.SEVERE, null, ex);
        }
        objBaixa.setDiasAtraso(Integer.valueOf(jDiasAtraso.getText()));
        pVALOR_DIARIO = (objBaixa.getValorPRBaixa() / 30);// ACHA O VALOR DO DIA   
        //
        pVALOR_TOTAL_PARCIAL = (pVALOR_DIARIO * objBaixa.getDiasAtraso()); // VALOR TOTAL DOS DIAS
        pVALOR_JUROS = (pVALOR_TOTAL_PARCIAL * objBaixa.getJurosDias() / 100); // VALOR TOTAL DOS JUROS
        pVALOR_TOTAL_OPERACAO = ((pVALOR_TOTAL_PARCIAL * objBaixa.getJurosDias()) / 100);
        pVALOR_TOTAL_OPERACAO = pVALOR_TOTAL_OPERACAO + objBaixa.getValorPRBaixa();
        objBaixa.setValorOperacao(pVALOR_TOTAL_OPERACAO);
        DecimalFormat vd = new DecimalFormat("#,##0.00");
        String vlDoc = vd.format(pVALOR_TOTAL_OPERACAO);
        jValorOperacao.setText(vlDoc);
        //
        DecimalFormat vj = new DecimalFormat("#,##0.00");
        String vlDocj = vj.format(pVALOR_JUROS);
        jValorJuros.setText(vlDocj);
    }//GEN-LAST:event_jBtCalcularActionPerformed

    private void jBtImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtImprimirActionPerformed
        // TODO add your handling code here:
        if (jCodigoOperacao.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "É necessário ter um registro baixado para realizar a impressão.");
        } else {

        }
    }//GEN-LAST:event_jBtImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBaixaCPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBaixaCPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBaixaCPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBaixaCPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaBaixaCPR dialog = new TelaBaixaCPR(pMOVI_CONTAS_PR, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCalcular;
    private javax.swing.JButton jBtConfirmar;
    private javax.swing.JButton jBtImprimir;
    private javax.swing.JButton jBtSair;
    private javax.swing.JComboBox<Object> jCentroCustoBaixa;
    private javax.swing.JComboBox<Object> jClienteFornecedorBaixa;
    private javax.swing.JTextField jCodigoOperacao;
    public static javax.swing.JComboBox<Object> jComboBoxAgenciaBaixa;
    public static javax.swing.JComboBox<Object> jComboBoxContaBanco;
    public static javax.swing.JComboBox<String> jComboBoxOperacaoBaixa;
    public static com.toedter.calendar.JDateChooser jDataEmissaoBaixa;
    private com.toedter.calendar.JDateChooser jDataOperacao;
    public static com.toedter.calendar.JDateChooser jDataVencimentoOperacao;
    private javax.swing.JFormattedTextField jDiasAtraso;
    public static javax.swing.JTextField jDocumentoBaixa;
    private javax.swing.JFormattedTextField jJurosDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<Object> jTipoDespesaBaixa;
    private javax.swing.JComboBox<Object> jTipoPagamentoBaixa;
    private javax.swing.JFormattedTextField jValorJuros;
    public static javax.swing.JFormattedTextField jValorOperacao;
    public static javax.swing.JFormattedTextField jValorPRBaixa;
    // End of variables declaration//GEN-END:variables

    public void corCampos() {
        jDocumentoBaixa.setBackground(Color.white);
        jCodigoOperacao.setBackground(Color.white);
        jValorOperacao.setBackground(Color.white);
        jValorPRBaixa.setBackground(Color.white);
    }

    public void buscarOperacao() {
        jDataOperacao.setCalendar(Calendar.getInstance());
        jComboBoxOperacaoBaixa.setSelectedItem(jComboBoxOperacao.getSelectedItem());
        jDataEmissaoBaixa.setDate(jDataEmissao.getDate());
        jDocumentoBaixa.setText(jNumeroDocumento.getText());
        jDataVencimentoOperacao.setDate(jDataVencimento.getDate());
        jTipoDespesaBaixa.addItem(jComboBoxTipoDespesa.getSelectedItem());
        jCentroCustoBaixa.addItem(jComboBoxCentroCusto.getSelectedItem());
        jValorPRBaixa.setText(jValorDocumento.getText());
        jValorOperacao.setText(jValorDocumento.getText());
        jClienteFornecedorBaixa.addItem(jComboBoxFornecedorCliente.getSelectedItem());
        jTipoPagamentoBaixa.addItem(jComboBoxTipoPagamento.getSelectedItem());
        jComboBoxAgenciaBaixa.addItem(jComboBoxBanco.getSelectedItem());
        jComboBoxContaBanco.addItem(jComboBoxContaCorrente.getSelectedItem());
        //
        jBtConfirmar.setEnabled(true);
    }

    public void mostrarBaixa() {
        if (jComboBoxOperacao.getSelectedItem().equals("Pagar")) {
            conecta.abrirConexao();
            try {
                conecta.executaSQL("SELECT * FROM BAIXA_CONTAS_PAGAR_RECEBER "
                        + "INNER JOIN MOVIMENTO_CONTAS_PAGAR_RECEBER "
                        + "ON BAIXA_CONTAS_PAGAR_RECEBER.IdMov=MOVIMENTO_CONTAS_PAGAR_RECEBER.IdMov "
                        + "INNER JOIN TIPO_CONTA "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdConta=TIPO_CONTA.IdConta "
                        + "INNER JOIN CENTRO_CUSTO "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdCentro=CENTRO_CUSTO.IdCentro "
                        + "INNER JOIN BANCOS_CONTAS "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdBanco=BANCOS_CONTAS.IdBanco "
                        + "INNER JOIN TIPO_PAGAMENTO "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdForma=TIPO_PAGAMENTO.IdForma "
                        + "INNER JOIN FORNECEDORES_AC "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdForn=FORNECEDORES_AC.IdForn "
                        + "WHERE BAIXA_CONTAS_PAGAR_RECEBER.IdMov='" + jCodigo.getText() + "'");
                conecta.rs.first();
                jCodigoOperacao.setText(conecta.rs.getString("IdBaixa"));
                jDataOperacao.setDate(conecta.rs.getDate("DataEmissao"));
                jComboBoxOperacaoBaixa.setSelectedItem(conecta.rs.getString("Operacao"));
                jDataEmissaoBaixa.setDate(conecta.rs.getDate("DataEmissao"));
                jDocumentoBaixa.setText(conecta.rs.getString("Documento"));
                jDataVencimentoOperacao.setDate(conecta.rs.getDate("DataVenc"));
                jTipoDespesaBaixa.addItem(conecta.rs.getString("DescricaoConta"));
                jCentroCustoBaixa.addItem(conecta.rs.getString("DescricaoCentro"));
                pCODIGO_BANCO = conecta.rs.getString("IdBanco");
                //
                pVALOR_DOCUMENTO_REAL = conecta.rs.getFloat("ValorBaixa");
                DecimalFormat vd = new DecimalFormat("#,##0.00");
                String vlDoc = vd.format(pVALOR_DOCUMENTO_REAL);
                jValorOperacao.setText(vlDoc);
                //
                pVALOR_BAIXA = conecta.rs.getFloat("ValorDoc");
                DecimalFormat vdB = new DecimalFormat("#,##0.00");
                String vlDocBaixa = vdB.format(pVALOR_BAIXA);
                jValorPRBaixa.setText(vlDocBaixa);
                //
                jClienteFornecedorBaixa.addItem(conecta.rs.getString("RazaoSocial"));
                jTipoPagamentoBaixa.addItem(conecta.rs.getString("DescricaoForma"));
                jDiasAtraso.setText(conecta.rs.getString("DiasAtraso"));
                //
                pJUROS_PESQUISA = conecta.rs.getFloat("JurosDia");
                DecimalFormat vdJP = new DecimalFormat("#,##0.00");
                String vl_JUROS = vdJP.format(pJUROS_PESQUISA);
                jJurosDia.setText(vl_JUROS);
                //
                pVALOR_JUROS_PESQUISA = conecta.rs.getFloat("ValorJuros");
                DecimalFormat vJP = new DecimalFormat("#,##0.00");
                String vl_JUROS_PESQUISA = vJP.format(pVALOR_JUROS_PESQUISA);
                jValorJuros.setText(vl_JUROS_PESQUISA);
                //
                jComboBoxAgenciaBaixa.addItem(conecta.rs.getString("Agencia"));
                jComboBoxContaBanco.addItem(conecta.rs.getString("ContaCorrente"));
            } catch (Exception e) {
            }
            conecta.desconecta();
        } else if (jComboBoxOperacao.getSelectedItem().equals("Receber")) {
            conecta.abrirConexao();
            try {
                conecta.executaSQL("SELECT * FROM BAIXA_CONTAS_PAGAR_RECEBER "
                        + "INNER JOIN MOVIMENTO_CONTAS_PAGAR_RECEBER "
                        + "ON BAIXA_CONTAS_PAGAR_RECEBER.IdMov=MOVIMENTO_CONTAS_PAGAR_RECEBER.IdMov "
                        + "INNER JOIN TIPO_CONTA "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdConta=TIPO_CONTA.IdConta "
                        + "INNER JOIN CENTRO_CUSTO "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdCentro=CENTRO_CUSTO.IdCentro "
                        + "INNER JOIN BANCOS_CONTAS "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdBanco=BANCOS_CONTAS.IdBanco "
                        + "INNER JOIN TIPO_PAGAMENTO "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdForma=TIPO_PAGAMENTO.IdForma "
                        + "INNER JOIN CLIENTES "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdForn=CLIENTES.IdClie "
                        + "WHERE BAIXA_CONTAS_PAGAR_RECEBER.IdMov='" + jCodigo.getText() + "'");
                conecta.rs.first();
                jCodigoOperacao.setText(conecta.rs.getString("IdBaixa"));
                jDataOperacao.setDate(conecta.rs.getDate("DataEmissao"));
                jComboBoxOperacaoBaixa.setSelectedItem(conecta.rs.getString("Operacao"));
                jDataEmissaoBaixa.setDate(conecta.rs.getDate("DataEmissao"));
                jDocumentoBaixa.setText(conecta.rs.getString("Documento"));
                jDataVencimentoOperacao.setDate(conecta.rs.getDate("DataVenc"));
                jTipoDespesaBaixa.addItem(conecta.rs.getString("DescricaoConta"));
                jCentroCustoBaixa.addItem(conecta.rs.getString("DescricaoCentro"));
                pCODIGO_BANCO = conecta.rs.getString("IdBanco");
                //
                pVALOR_DOCUMENTO_REAL = conecta.rs.getFloat("ValorBaixa");
                DecimalFormat vd = new DecimalFormat("#,##0.00");
                String vlDoc = vd.format(pVALOR_DOCUMENTO_REAL);
                jValorOperacao.setText(vlDoc);
                //
                pVALOR_BAIXA = conecta.rs.getFloat("ValorDoc");
                DecimalFormat vdB = new DecimalFormat("#,##0.00");
                String vlDocBaixa = vdB.format(pVALOR_BAIXA);
                jValorPRBaixa.setText(vlDocBaixa);
                //
                jClienteFornecedorBaixa.addItem(conecta.rs.getString("RazaoSocial"));
                jTipoPagamentoBaixa.addItem(conecta.rs.getString("DescricaoForma"));
                jDiasAtraso.setText(conecta.rs.getString("DiasAtraso"));
                //
                pJUROS_PESQUISA = conecta.rs.getFloat("ValorJuros");
                DecimalFormat vdJP = new DecimalFormat("#,##0.00");
                String vl_JUROS = vdJP.format(pVALOR_BAIXA);
                jJurosDia.setText(vl_JUROS);
                //
                pVALOR_JUROS_PESQUISA = conecta.rs.getFloat("ValorJuros");
                DecimalFormat vJP = new DecimalFormat("#,##0.00");
                String vl_JUROS_PESQUISA = vJP.format(pVALOR_JUROS_PESQUISA);
                jValorJuros.setText(vl_JUROS_PESQUISA);
                //
                jComboBoxAgenciaBaixa.addItem(conecta.rs.getString("Agencia"));
                jComboBoxContaBanco.addItem(conecta.rs.getString("ContaCorrente"));
            } catch (Exception e) {
            }
            conecta.desconecta();
        }
    }

    public void verificarBaixa() {
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM BAIXA_CONTAS_PAGAR_RECEBER "
                    + "WHERE IdMov='" + jCodigo.getText() + "'");
            conecta.rs.first();
            pCODIGO_MOV_BAIXA = conecta.rs.getString("IdMov");
        } catch (Exception e) {
        }
        conecta.desconecta();
    }

    public void pesquisaSaldoBancario() {
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM SALDO_BANCARIO "
                    + "INNER JOIN BANCOS_CONTAS "
                    + "ON SALDO_BANCARIO.IdBanco=BANCOS_CONTAS.IdBanco "
                    + "WHERE BANCOS_CONTAS.IdBanco='" + pCODIGO_BANCO + "' "
                    + "AND Agencia='" + jComboBoxAgenciaBaixa.getSelectedItem().toString().trim() + "'");
            conecta.rs.last();
            pSALDO_BANCARIO = conecta.rs.getFloat("SaldoAtual");
        } catch (Exception e) {
        }
        conecta.desconecta();
    }

    public void pesquisarRegistros() {
        if (jComboBoxOperacaoBaixa.getSelectedItem().equals("Pagar")) {
            FornecedoresDAO dao = new FornecedoresDAO();
            try {
                for (Fornecedor p : dao.read()) {
                    jClienteFornecedorBaixa.addItem(p);
                }
            } catch (Exception ex) {
                Logger.getLogger(TelaBaixaCPR.class.getName()).log(Level.SEVERE, null, ex);
            }
            Fornecedor fornecedor = (Fornecedor) jClienteFornecedorBaixa.getSelectedItem();
            fornecedor.getIdForn();
            fornecedor.getRazaoSocial();
            objBaixa.setIdForn(fornecedor.getIdForn());
        } else if (jComboBoxOperacaoBaixa.getSelectedItem().equals("Receber")) {
            ClientesDAO dao = new ClientesDAO();
            try {
                for (Clientes c : dao.read()) {
                    jComboBoxFornecedorCliente.addItem(c);
                }
            } catch (Exception ex) {
                Logger.getLogger(TelaMovimentacaoContasPR.class.getName()).log(Level.SEVERE, null, ex);
            }
            Clientes cliente = (Clientes) jComboBoxFornecedorCliente.getSelectedItem();
            cliente.getIdForn();
            cliente.getRazaoSocial();
            objBaixa.setIdForn(cliente.getIdForn());
        }
    }

    public void Confirmar() {
        jValorPRBaixa.setEnabled(!true);
        jValorOperacao.setEnabled(!true);
        jDiasAtraso.setEnabled(!true);
        jJurosDia.setEnabled(!true);
        jValorJuros.setEnabled(!true);
        jComboBoxContaBanco.setEnabled(!true);
        jBtConfirmar.setEnabled(!true);
        jBtCalcular.setEnabled(!true);
    }

    public void buscarCodigo() {
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM BAIXA_CONTAS_PAGAR_RECEBER");
            conecta.rs.last();
            jCodigoOperacao.setText(conecta.rs.getString("IdBaixa"));
        } catch (Exception e) {
        }
        conecta.desconecta();
    }
}
