/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Dao.ConexaoBancoDados;
import Util.ModeloTabela;
import static Visao.TelaPrincipal.tipoServidor;
import java.awt.Color;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author ronal
 */
public class TelaFluxoCaixa extends javax.swing.JInternalFrame {

    ConexaoBancoDados conecta = new ConexaoBancoDados();

    int count = 0;
    int flag = 0;
    int acao = 0;
    String dataInicial, dataFinal, dataVenc;
    ;
    String pTIPO_OPERCAO_DEBITO = "D";
    String pTIPO_OPERCAO_CREDITO = "C";
    String pSTATUS_BANCO = "Ativo";
    String pVALOR_DOCUMENTO = "";
    float pVALOR_DOCUMENTO_REAL = 0;
    public static String pOPERACAO_PAGAR_CONSULTA = "Pagar";
    public static String pOPERACAO_RECEBER_CONSULTA = "Receber";
    public static String pOPERACAO_CONTAS_PR = "";
    String pOPERACAO_PAGAR_RECEBER = "";
    String pCODIGO_MOV_BAIXA = "";
    String pCONTA_BAIXADA = "Sim";
    //
    public static String idLancFluxo;
    //
    float pVALOR_TOTAL_RECEITAS_DESPESAS = 0;
    String pVALOR_TOTAL_TABELA;

    public static TelaBaixaConsultaFluxo pBAIXA_CPR;
    public static TelaConsultaContasPagasRecebidasFluxo pCONSULTAS_CONTAS_PAGAS;

    /**
     * Creates new form TelaConsultasPagasRecebidas
     */
    public TelaFluxoCaixa() {
        initComponents();
        corCampos();
    }

    public void mostraTelaBaixa() {
        pBAIXA_CPR = new TelaBaixaConsultaFluxo(this, true);
        pBAIXA_CPR.setVisible(true);
    }

    public void mostraTelaContas() {
        pCONSULTAS_CONTAS_PAGAS = new TelaConsultaContasPagasRecebidasFluxo(this, true);
        pCONSULTAS_CONTAS_PAGAS.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDataPesqInicial = new com.toedter.calendar.JDateChooser();
        jDataPesqFinal = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jDocumento = new javax.swing.JFormattedTextField();
        jBtPesquisarDocumento = new javax.swing.JButton();
        jBtPesquisarContaData = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTotalDespesas = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jTotalReceitas = new javax.swing.JFormattedTextField();
        jPanel33 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jtotalRegistros = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabelaContas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jBtBuscarBaixa = new javax.swing.JButton();
        jBtSair = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("...::: Fluxo de Caixa :::...");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("DATA INICIAL");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("DATA FINAL");

        jDataPesqInicial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jDataPesqFinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("PESQUISAR POR Nº DOCUMENTO");

        jDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jDocumento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jBtPesquisarDocumento.setForeground(new java.awt.Color(0, 0, 255));
        jBtPesquisarDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Lupas_1338_05.gif"))); // NOI18N
        jBtPesquisarDocumento.setText("Pesquisar");
        jBtPesquisarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisarDocumentoActionPerformed(evt);
            }
        });

        jBtPesquisarContaData.setForeground(new java.awt.Color(0, 0, 255));
        jBtPesquisarContaData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Lupas_1338_05.gif"))); // NOI18N
        jBtPesquisarContaData.setText("Pesquisar");
        jBtPesquisarContaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisarContaDataActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("TOTAL DAS DESPESAS");

        jTotalDespesas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTotalDespesas.setForeground(new java.awt.Color(204, 0, 0));
        jTotalDespesas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTotalDespesas.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        jTotalDespesas.setEnabled(false);
        jTotalDespesas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("TOTAL DAS RECEITAS");

        jTotalReceitas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTotalReceitas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTotalReceitas.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jDocumento, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtPesquisarDocumento))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jDataPesqInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDataPesqFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtPesquisarContaData))
                            .addComponent(jLabel3))))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTotalDespesas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTotalReceitas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jDataPesqInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDataPesqFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtPesquisarContaData))
                    .addComponent(jTotalReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtPesquisarDocumento)
                    .addComponent(jTotalDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel33.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        jLabel67.setText("Total de Registros:");

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel67))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel67)
        );

        jPanel35.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jPanel34.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        jtotalRegistros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtotalRegistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtotalRegistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
        );

        jTabelaContas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTabelaContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Venc.", "Nº Doc.", "Valor R$", "Operação", "Tipo Pagto", "Centro Custo", "Despesa/Receita", "Cliente/Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaContasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTabelaContas);
        if (jTabelaContas.getColumnModel().getColumnCount() > 0) {
            jTabelaContas.getColumnModel().getColumn(0).setMinWidth(80);
            jTabelaContas.getColumnModel().getColumn(0).setMaxWidth(80);
            jTabelaContas.getColumnModel().getColumn(1).setMinWidth(80);
            jTabelaContas.getColumnModel().getColumn(1).setMaxWidth(80);
            jTabelaContas.getColumnModel().getColumn(2).setMinWidth(90);
            jTabelaContas.getColumnModel().getColumn(2).setMaxWidth(90);
            jTabelaContas.getColumnModel().getColumn(3).setMinWidth(100);
            jTabelaContas.getColumnModel().getColumn(3).setMaxWidth(100);
            jTabelaContas.getColumnModel().getColumn(4).setMinWidth(80);
            jTabelaContas.getColumnModel().getColumn(4).setMaxWidth(80);
            jTabelaContas.getColumnModel().getColumn(5).setMinWidth(250);
            jTabelaContas.getColumnModel().getColumn(5).setMaxWidth(250);
            jTabelaContas.getColumnModel().getColumn(6).setMinWidth(300);
            jTabelaContas.getColumnModel().getColumn(6).setMaxWidth(300);
            jTabelaContas.getColumnModel().getColumn(7).setMinWidth(250);
            jTabelaContas.getColumnModel().getColumn(7).setMaxWidth(250);
            jTabelaContas.getColumnModel().getColumn(8).setMinWidth(350);
            jTabelaContas.getColumnModel().getColumn(8).setMaxWidth(350);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        jBtBuscarBaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/kde-file-downloads-icone-4393-32.png"))); // NOI18N
        jBtBuscarBaixa.setText("Baixa");
        jBtBuscarBaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtBuscarBaixa.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtBuscarBaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtBuscarBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtBuscarBaixaActionPerformed(evt);
            }
        });

        jBtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Log_Out_Icon_32.png"))); // NOI18N
        jBtSair.setText("Sair");
        jBtSair.setToolTipText("Sair");
        jBtSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtSair.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jBtBuscarBaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtSair)
                .addGap(60, 60, 60))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtBuscarBaixa, jBtSair});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtBuscarBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtBuscarBaixa, jBtSair});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        setBounds(300, 30, 795, 483);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtPesquisarContaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisarContaDataActionPerformed
        // TODO add your handling code here:
        flag = 1;
        if (tipoServidor == null || tipoServidor.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "É necessário definir o parâmtero para o sistema operacional utilizado no servidor, (UBUNTU-LINUX ou WINDOWS SERVER).");
        } else if (tipoServidor.equals("Servidor Linux (Ubuntu)/MS-SQL Server")) {
            if (jDataPesqInicial.getDate() == null) {
                JOptionPane.showMessageDialog(rootPane, "Informe a data inicial para pesquisa.");
                jDataPesqInicial.requestFocus();
            } else if (jDataPesqFinal.getDate() == null) {
                JOptionPane.showMessageDialog(rootPane, "Informe a data final para pesquisa.");
                jDataPesqFinal.requestFocus();
            } else if (jDataPesqInicial.getDate().after(jDataPesqFinal.getDate())) {
                JOptionPane.showMessageDialog(rootPane, "Data Inicial não pode ser maior que data final");
            } else {
                SimpleDateFormat formatoAmerica = new SimpleDateFormat("yyyy/MM/dd");
                dataInicial = formatoAmerica.format(jDataPesqInicial.getDate().getTime());
                dataFinal = formatoAmerica.format(jDataPesqFinal.getDate().getTime());
                preencherTabelaMovimentacaoCPR("SELECT * FROM MOVIMENTO_CONTAS_PAGAR_RECEBER "
                        + "INNER JOIN BANCOS_CONTAS "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdBanco=BANCOS_CONTAS.IdBanco "
                        + "INNER JOIN CENTRO_CUSTO "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdCentro=CENTRO_CUSTO.IdCentro "
                        + "INNER JOIN TIPO_CONTA "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdConta=TIPO_CONTA.IdConta "
                        + "INNER JOIN TIPO_PAGAMENTO "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdForma=TIPO_PAGAMENTO.IdForma "
                        + "WHERE MOVIMENTO_CONTAS_PAGAR_RECEBER.DataEmissao BETWEEN'" + dataInicial + "' "
                        + "AND '" + dataFinal + "' "
                        + "AND MOVIMENTO_CONTAS_PAGAR_RECEBER.ContaBaixada='" + pCONTA_BAIXADA + "'");
            }
        } else if (tipoServidor.equals("Servidor Windows/MS-SQL Server")) {
            if (jDataPesqInicial.getDate() == null) {
                JOptionPane.showMessageDialog(rootPane, "Informe a data inicial para pesquisa.");
                jDataPesqInicial.requestFocus();
            } else if (jDataPesqFinal.getDate() == null) {
                JOptionPane.showMessageDialog(rootPane, "Informe a data final para pesquisa.");
                jDataPesqFinal.requestFocus();
            } else if (jDataPesqInicial.getDate().after(jDataPesqFinal.getDate())) {
                JOptionPane.showMessageDialog(rootPane, "Data Inicial não pode ser maior que data final");
            } else {
                SimpleDateFormat formatoAmerica = new SimpleDateFormat("dd/MM/yyyy");
                dataInicial = formatoAmerica.format(jDataPesqInicial.getDate().getTime());
                dataFinal = formatoAmerica.format(jDataPesqFinal.getDate().getTime());
                preencherTabelaMovimentacaoCPR("SELECT * FROM MOVIMENTO_CONTAS_PAGAR_RECEBER "
                        + "INNER JOIN BANCOS_CONTAS "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdBanco=BANCOS_CONTAS.IdBanco "
                        + "INNER JOIN CENTRO_CUSTO "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdCentro=CENTRO_CUSTO.IdCentro "
                        + "INNER JOIN TIPO_CONTA "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdConta=TIPO_CONTA.IdConta "
                        + "INNER JOIN TIPO_PAGAMENTO "
                        + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdForma=TIPO_PAGAMENTO.IdForma "
                        + "WHERE MOVIMENTO_CONTAS_PAGAR_RECEBER.DataEmissao BETWEEN'" + dataInicial + "' "
                        + "AND '" + dataFinal + "' "
                        + "AND MOVIMENTO_CONTAS_PAGAR_RECEBER.ContaBaixada='" + pCONTA_BAIXADA + "' ");
            }
        }
    }//GEN-LAST:event_jBtPesquisarContaDataActionPerformed

    private void jBtPesquisarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisarDocumentoActionPerformed
        // TODO add your handling code here:
        if (jDocumento.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe o número do documento para pesquisa.");
        } else {
            preencherTabelaMovimentacaoCPR("SELECT * FROM MOVIMENTO_CONTAS_PAGAR_RECEBER "
                    + "INNER JOIN BANCOS_CONTAS "
                    + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdBanco=BANCOS_CONTAS.IdBanco "
                    + "INNER JOIN CENTRO_CUSTO "
                    + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdCentro=CENTRO_CUSTO.IdCentro "
                    + "INNER JOIN TIPO_CONTA "
                    + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdConta=TIPO_CONTA.IdConta "
                    + "INNER JOIN TIPO_PAGAMENTO "
                    + "ON MOVIMENTO_CONTAS_PAGAR_RECEBER.IdForma=TIPO_PAGAMENTO.IdForma "
                    + "WHERE MOVIMENTO_CONTAS_PAGAR_RECEBER.Documento='" + jDocumento.getText() + "' "
                    + "AND MOVIMENTO_CONTAS_PAGAR_RECEBER.ContaBaixada='" + pCONTA_BAIXADA + "'");
        }
    }//GEN-LAST:event_jBtPesquisarDocumentoActionPerformed

    private void jBtBuscarBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtBuscarBaixaActionPerformed
        // TODO add your handling code here:
        if (idLancFluxo == null) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um registro para consultar a baixa.");
        } else if (idLancFluxo.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um registro para consultar a baixa.");
        } else {
            mostraTelaBaixa();
        }
    }//GEN-LAST:event_jBtBuscarBaixaActionPerformed

    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtSairActionPerformed

    private void jTabelaContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaContasMouseClicked
        // TODO add your handling code here:
        flag = 1;
        if (flag == 1) {
            idLancFluxo = "" + jTabelaContas.getValueAt(jTabelaContas.getSelectedRow(), 0);
            pOPERACAO_CONTAS_PR = "" + jTabelaContas.getValueAt(jTabelaContas.getSelectedRow(), 4);
//            mostraTelaContas();
        }
    }//GEN-LAST:event_jTabelaContasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtBuscarBaixa;
    private javax.swing.JButton jBtPesquisarContaData;
    private javax.swing.JButton jBtPesquisarDocumento;
    private javax.swing.JButton jBtSair;
    private com.toedter.calendar.JDateChooser jDataPesqFinal;
    private com.toedter.calendar.JDateChooser jDataPesqInicial;
    private javax.swing.JFormattedTextField jDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTabelaContas;
    private javax.swing.JFormattedTextField jTotalDespesas;
    private javax.swing.JFormattedTextField jTotalReceitas;
    public static javax.swing.JLabel jtotalRegistros;
    // End of variables declaration//GEN-END:variables

    public void corCampos() {
        jTotalReceitas.setBackground(Color.white);
        jTotalDespesas.setBackground(Color.white);
    }

    public void preencherTabelaMovimentacaoCPR(String sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código ", "Venc. ", "NºDoc.", "Valor R$", "Operação", "Tipo Pagto", "Centro Custo", "Despesa/Receita"};
        conecta.abrirConexao();
        try {
            conecta.executaSQL(sql);
            conecta.rs.first();
            count = 0;
            pVALOR_TOTAL_RECEITAS_DESPESAS = 0;
            do {
                count = count + 1;
                pVALOR_TOTAL_TABELA = "0,00";
                jTotalDespesas.setText(pVALOR_TOTAL_TABELA);
                jTotalDespesas.setForeground(Color.red);
                // Formatar a data no formato Brasil
                dataVenc = conecta.rs.getString("DataVenc");
                String dia = dataVenc.substring(8, 10);
                String mes = dataVenc.substring(5, 7);
                String ano = dataVenc.substring(0, 4);
                dataVenc = dia + "/" + mes + "/" + ano;
                //
                pVALOR_DOCUMENTO_REAL = conecta.rs.getFloat("ValorDoc");
                DecimalFormat vd = new DecimalFormat("#,##0.00");
                String vlDoc = vd.format(pVALOR_DOCUMENTO_REAL);
                pVALOR_DOCUMENTO = vlDoc;
                //
                jtotalRegistros.setText(Integer.toString(count));
                //TOTALIZADOR DAS RECEITAS/DESPESAS
                pVALOR_TOTAL_RECEITAS_DESPESAS = pVALOR_TOTAL_RECEITAS_DESPESAS + pVALOR_DOCUMENTO_REAL;
                //CONVERTER PARA MOSTRAR NA TELA
                DecimalFormat vtrd = new DecimalFormat("#,##0.00");
                String vltrd = vtrd.format(pVALOR_TOTAL_RECEITAS_DESPESAS);
                pVALOR_TOTAL_TABELA = vltrd;
                jTotalDespesas.setText(pVALOR_TOTAL_TABELA);
                dados.add(new Object[]{conecta.rs.getString("IdMov"), dataVenc, conecta.rs.getString("Documento"), pVALOR_DOCUMENTO, conecta.rs.getString("Operacao"), conecta.rs.getString("DescricaoForma"), conecta.rs.getString("DescricaoCentro"), conecta.rs.getString("DescricaoConta")});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não existem dados a serem EXIBIDOS!!!");
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaContas.setModel(modelo);
        jTabelaContas.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTabelaContas.getColumnModel().getColumn(0).setResizable(false);
        jTabelaContas.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTabelaContas.getColumnModel().getColumn(1).setResizable(false);
        jTabelaContas.getColumnModel().getColumn(2).setPreferredWidth(90);
        jTabelaContas.getColumnModel().getColumn(2).setResizable(false);
        jTabelaContas.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTabelaContas.getColumnModel().getColumn(3).setResizable(false);
        jTabelaContas.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTabelaContas.getColumnModel().getColumn(4).setResizable(false);
        jTabelaContas.getColumnModel().getColumn(5).setPreferredWidth(250);
        jTabelaContas.getColumnModel().getColumn(5).setResizable(false);
        jTabelaContas.getColumnModel().getColumn(6).setPreferredWidth(300);
        jTabelaContas.getColumnModel().getColumn(6).setResizable(false);
        jTabelaContas.getColumnModel().getColumn(7).setPreferredWidth(250);
        jTabelaContas.getColumnModel().getColumn(7).setResizable(false);
        jTabelaContas.setAutoResizeMode(jTabelaContas.AUTO_RESIZE_OFF);
        jTabelaContas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        alinharCamposTabelaCPR();
        conecta.desconecta();
    }

    public void limparTabelaCPR() {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código ", "Venc. ", "NºDoc.", "Valor R$", "Operação", "Tipo Pagto", "Centro Custo", "Despesa/Receita", "Cliente/Fornecedor"};
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaContas.setModel(modelo);
        jTabelaContas.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTabelaContas.getColumnModel().getColumn(0).setResizable(false);
        jTabelaContas.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTabelaContas.getColumnModel().getColumn(1).setResizable(false);
        jTabelaContas.getColumnModel().getColumn(2).setPreferredWidth(90);
        jTabelaContas.getColumnModel().getColumn(2).setResizable(false);
        jTabelaContas.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTabelaContas.getColumnModel().getColumn(3).setResizable(false);
        jTabelaContas.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTabelaContas.getColumnModel().getColumn(4).setResizable(false);
        jTabelaContas.getColumnModel().getColumn(5).setPreferredWidth(250);
        jTabelaContas.getColumnModel().getColumn(5).setResizable(false);
        jTabelaContas.getColumnModel().getColumn(6).setPreferredWidth(300);
        jTabelaContas.getColumnModel().getColumn(6).setResizable(false);
        jTabelaContas.getColumnModel().getColumn(7).setPreferredWidth(250);
        jTabelaContas.getColumnModel().getColumn(7).setResizable(false);
        jTabelaContas.setAutoResizeMode(jTabelaContas.AUTO_RESIZE_OFF);
        jTabelaContas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        modelo.getLinhas().clear();
    }

    public void alinharCamposTabelaCPR() {
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        //
        jTabelaContas.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        jTabelaContas.getColumnModel().getColumn(1).setCellRenderer(centralizado);
        jTabelaContas.getColumnModel().getColumn(2).setCellRenderer(centralizado);
        jTabelaContas.getColumnModel().getColumn(3).setCellRenderer(direita);
    }
}
