/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Dao.ConexaoBancoDados;
import Dao.ListaCentroCustoDAO_CP_CONSULTAS;
import Dao.ListaCentroCustoDAO_CR_CONSULTAS;
import Dao.ListarBancosDAO_CP_CONSULTAS;
import Dao.ListarBancosDAO_CR_CONSULTAS;
import Dao.ListarClientesDAO_CONSULTAS;
import Dao.ListarFormaPagamentoDAO_CP_CONSULTAS;
import Dao.ListarFormaPagamentoDAO_CR_CONSULTAS;
import Dao.ListarFornecedorDAO_CP_CONSULTAS;
import Dao.ListarTiposContasDAO_CP_CONSULTAS;
import Dao.ListarTiposContasDAO_CR_CONSULTAS;
import Modelo.BancosContas;
import Modelo.CentroCusto;
import Modelo.Clientes;
import Modelo.EmpresaUnidade;
import Modelo.FormaPagamento;
import Modelo.Fornecedor;
import Modelo.MovimentoCPR;
import Modelo.TipoConta;
import static Visao.TelaConsultasPagasRecebidas.idLanc;
import static Visao.TelaConsultasPagasRecebidas.pOPERACAO_CONTAS_PR;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ronal
 */
public class TelaConsultaContasPagasRecebidas extends javax.swing.JDialog {

    ConexaoBancoDados conecta = new ConexaoBancoDados();
    TipoConta objTipoConta = new TipoConta();
    FormaPagamento objPagto = new FormaPagamento();
    Fornecedor objForn = new Fornecedor();
    Clientes objClie = new Clientes();
    CentroCusto objCentro = new CentroCusto();
    BancosContas objBanco = new BancosContas();
    EmpresaUnidade objEmpUni = new EmpresaUnidade();
    MovimentoCPR objMov = new MovimentoCPR();
    //
    String pVALOR_DOCUMENTO = "";
    float pVALOR_DOCUMENTO_REAL = 0;

    /**
     * Creates new form TelaConsutaContasPagasRecebidas
     */
    public static TelaConsultasPagasRecebidas pCONSULTAS_CONTAS_PAGAS_RECEBIDAS;

    public TelaConsultaContasPagasRecebidas(TelaConsultasPagasRecebidas parent, boolean modal) {
        this.pCONSULTAS_CONTAS_PAGAS_RECEBIDAS = parent;
        this.setModal(modal);
        setLocationRelativeTo(pCONSULTAS_CONTAS_PAGAS_RECEBIDAS);
        initComponents();
        corCampos();
        formatarCampos();
        buscarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxOperacao = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDataEmissao = new com.toedter.calendar.JDateChooser();
        jDataVencimento = new com.toedter.calendar.JDateChooser();
        jNumeroDocumento = new javax.swing.JFormattedTextField();
        jValorDocumento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxTipoPagamento = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxFornecedorCliente = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxContaCorrente = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxCentroCusto = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jHistorico = new javax.swing.JTextArea();
        jComboBoxTipoDespesa = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCodigo = new javax.swing.JTextField();
        jComboBoxBanco = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("...::: Consulta Contas Pagas Recebidas :::...");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("OPERAÇÃO");

        jComboBoxOperacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxOperacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Pagar", "Receber" }));
        jComboBoxOperacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBoxOperacao.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("DATA EMISSÃO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("DATA VENC.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nº DOC.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("VALOR R$");

        jDataEmissao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jDataEmissao.setEnabled(false);

        jDataVencimento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jDataVencimento.setEnabled(false);

        jNumeroDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jNumeroDocumento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jNumeroDocumento.setEnabled(false);

        jValorDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jValorDocumento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jValorDocumento.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("TIPO PAGAMENTO");

        jComboBoxTipoPagamento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxTipoPagamento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBoxTipoPagamento.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("CLIENTE/FORNECEDOR");

        jComboBoxFornecedorCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxFornecedorCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBoxFornecedorCliente.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("BANCO");

        jComboBoxContaCorrente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxContaCorrente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBoxContaCorrente.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("CENTRO DE CUSTO");

        jComboBoxCentroCusto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxCentroCusto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBoxCentroCusto.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("CONTA CORRENTE");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("HISTÓRICO");

        jHistorico.setColumns(20);
        jHistorico.setRows(5);
        jHistorico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jHistorico.setEnabled(false);
        jScrollPane1.setViewportView(jHistorico);

        jComboBoxTipoDespesa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxTipoDespesa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBoxTipoDespesa.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("TIPO DE DESPESA/RECEITA");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("CÓDIGO");

        jCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jCodigo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jCodigo.setEnabled(false);

        jComboBoxBanco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxBanco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBoxBanco.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jComboBoxOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jValorDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxContaCorrente, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipoDespesa, javax.swing.GroupLayout.Alignment.LEADING, 0, 386, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jComboBoxFornecedorCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jComboBoxCentroCusto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jComboBoxTipoPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxCentroCusto, jComboBoxFornecedorCliente, jComboBoxTipoDespesa, jComboBoxTipoPagamento});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxBanco, jDataEmissao});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel13)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(jDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel8)))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jValorDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxContaCorrente, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(jComboBoxFornecedorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(jComboBoxCentroCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(jComboBoxTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(6, 6, 6)
                .addComponent(jComboBoxTipoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaContasPagasRecebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaContasPagasRecebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaContasPagasRecebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaContasPagasRecebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaConsultaContasPagasRecebidas dialog = new TelaConsultaContasPagasRecebidas(pCONSULTAS_CONTAS_PAGAS_RECEBIDAS, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField jCodigo;
    public static javax.swing.JComboBox<Object> jComboBoxBanco;
    public static javax.swing.JComboBox<Object> jComboBoxCentroCusto;
    public static javax.swing.JComboBox<String> jComboBoxContaCorrente;
    public static javax.swing.JComboBox<Object> jComboBoxFornecedorCliente;
    public static javax.swing.JComboBox<String> jComboBoxOperacao;
    public static javax.swing.JComboBox<Object> jComboBoxTipoDespesa;
    public static javax.swing.JComboBox<Object> jComboBoxTipoPagamento;
    public static com.toedter.calendar.JDateChooser jDataEmissao;
    public static com.toedter.calendar.JDateChooser jDataVencimento;
    public static javax.swing.JTextArea jHistorico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JFormattedTextField jNumeroDocumento;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JFormattedTextField jValorDocumento;
    // End of variables declaration//GEN-END:variables

    public void corCampos() {
        jCodigo.setBackground(Color.white);
        jComboBoxOperacao.setBackground(Color.white);
        jDataEmissao.setBackground(Color.white);
        jDataVencimento.setBackground(Color.white);
        jNumeroDocumento.setBackground(Color.white);
        jValorDocumento.setBackground(Color.white);
        jComboBoxBanco.setBackground(Color.white);
        jComboBoxContaCorrente.setBackground(Color.white);
        jComboBoxFornecedorCliente.setBackground(Color.white);
        jComboBoxTipoPagamento.setBackground(Color.white);
        jComboBoxCentroCusto.setBackground(Color.white);
        jComboBoxTipoDespesa.setBackground(Color.white);
        jHistorico.setBackground(Color.white);
    }

    public void formatarCampos() {
        jHistorico.setLineWrap(true);
        jHistorico.setWrapStyleWord(true);
    }

    public void buscarDados() {
        if (pOPERACAO_CONTAS_PR.equals("Pagar")) {
            jComboBoxFornecedorCliente.removeAllItems();
            jComboBoxBanco.removeAllItems();
            jComboBoxContaCorrente.removeAllItems();
            jComboBoxTipoPagamento.removeAllItems();
            jComboBoxCentroCusto.removeAllItems();
            jComboBoxTipoDespesa.removeAllItems();
            conecta.abrirConexao();
            try {
                conecta.executaSQL("SELECT * FROM MOVIMENTO_CONTAS_PAGAR_RECEBER "
                        + "WHERE MOVIMENTO_CONTAS_PAGAR_RECEBER.IdMov='" + idLanc + "' "
                        + "AND Operacao='" + pOPERACAO_CONTAS_PR + "'");
                conecta.rs.first();
                jCodigo.setText(String.valueOf(conecta.rs.getInt("IdMov")));
                jComboBoxOperacao.setSelectedItem(conecta.rs.getString("Operacao"));
                jDataEmissao.setDate(conecta.rs.getDate("DataEmissao"));
                jDataVencimento.setDate(conecta.rs.getDate("DataVenc"));
                jNumeroDocumento.setText(conecta.rs.getString("Documento"));
                pVALOR_DOCUMENTO_REAL = conecta.rs.getFloat("ValorDoc");
                DecimalFormat vd = new DecimalFormat("#,##0.00");
                String vlDoc = vd.format(pVALOR_DOCUMENTO_REAL);
                jValorDocumento.setText(vlDoc);
                jHistorico.setText(conecta.rs.getString("Historico"));
            } catch (Exception e) {
            }
            //
            ListarFornecedorDAO_CP_CONSULTAS listaDAO = new ListarFornecedorDAO_CP_CONSULTAS();
            try {
                for (Fornecedor p : listaDAO.read()) {
                    jComboBoxFornecedorCliente.addItem(p);
                }
            } catch (Exception ex) {
                Logger.getLogger(TelaConsultaContasPagasRecebidas.class.getName()).log(Level.SEVERE, null, ex);
            }
            Fornecedor fornecedor = (Fornecedor) jComboBoxFornecedorCliente.getSelectedItem();
            fornecedor.getIdForn();
            fornecedor.getRazaoSocial();
            objMov.setIdForn(fornecedor.getIdForn());
            //
            ListarBancosDAO_CP_CONSULTAS listaBancos = new ListarBancosDAO_CP_CONSULTAS();
            try {
                for (BancosContas b : listaBancos.read()) {
                    jComboBoxBanco.addItem(b);
                }
            } catch (Exception ex) {
                Logger.getLogger(TelaConsultaContasPagasRecebidas.class.getName()).log(Level.SEVERE, null, ex);
            }
            BancosContas banco = (BancosContas) jComboBoxBanco.getSelectedItem();
            banco.getIdBanco();
            banco.getContaCorrente();
            objMov.setIdBanco(banco.getIdBanco());
            jComboBoxContaCorrente.addItem(banco.getContaCorrente());
            //
            ListarFormaPagamentoDAO_CP_CONSULTAS listaForma = new ListarFormaPagamentoDAO_CP_CONSULTAS();
            try {
                for (FormaPagamento f : listaForma.read()) {
                    jComboBoxTipoPagamento.addItem(f);
                }
            } catch (Exception ex) {
                Logger.getLogger(TelaConsultaContasPagasRecebidas.class.getName()).log(Level.SEVERE, null, ex);
            }
            FormaPagamento forma = (FormaPagamento) jComboBoxTipoPagamento.getSelectedItem();
            forma.getIdForma();
            forma.getDescricaoForma();
            objMov.setIdForma(forma.getIdForma());
            //
            ListaCentroCustoDAO_CP_CONSULTAS listaDAOCentro = new ListaCentroCustoDAO_CP_CONSULTAS();
            try {
                for (CentroCusto c : listaDAOCentro.read()) {
                    jComboBoxCentroCusto.addItem(c);
                }
            } catch (Exception ex) {
                Logger.getLogger(TelaConsultaContasPagasRecebidas.class.getName()).log(Level.SEVERE, null, ex);
            }
            CentroCusto centro = (CentroCusto) jComboBoxCentroCusto.getSelectedItem();
            centro.getIdCentro();
            centro.getDescricaoCentro();
            objMov.setIdCentro(centro.getIdCentro());
            //
            ListarTiposContasDAO_CP_CONSULTAS listarDAOContas = new ListarTiposContasDAO_CP_CONSULTAS();
            try {
                for (TipoConta t : listarDAOContas.read()) {
                    jComboBoxTipoDespesa.addItem(t);
                }
            } catch (Exception ex) {
                Logger.getLogger(TelaConsultaContasPagasRecebidas.class.getName()).log(Level.SEVERE, null, ex);
            }
            TipoConta tipo = (TipoConta) jComboBoxTipoDespesa.getSelectedItem();
            tipo.getIdConta();
            tipo.getDescricaoConta();
            objMov.setIdConta(tipo.getIdConta());
        } else if (pOPERACAO_CONTAS_PR.equals("Receber")) {
            jComboBoxFornecedorCliente.removeAllItems();
            jComboBoxBanco.removeAllItems();
            jComboBoxContaCorrente.removeAllItems();
            jComboBoxTipoPagamento.removeAllItems();
            jComboBoxCentroCusto.removeAllItems();
            jComboBoxTipoDespesa.removeAllItems();
            conecta.abrirConexao();
            try {
                conecta.executaSQL("SELECT * FROM MOVIMENTO_CONTAS_PAGAR_RECEBER "
                        + "WHERE MOVIMENTO_CONTAS_PAGAR_RECEBER.IdMov='" + idLanc + "' "
                        + "AND Operacao='" + pOPERACAO_CONTAS_PR + "'");
                conecta.rs.first();
                jCodigo.setText(conecta.rs.getString("IdMov"));
                jComboBoxOperacao.setSelectedItem(conecta.rs.getString("Operacao"));
                jDataEmissao.setDate(conecta.rs.getDate("DataEmissao"));
                jDataVencimento.setDate(conecta.rs.getDate("DataVenc"));
                jNumeroDocumento.setText(conecta.rs.getString("Documento"));
                pVALOR_DOCUMENTO_REAL = conecta.rs.getFloat("ValorDoc");
                DecimalFormat vd = new DecimalFormat("#,##0.00");
                String vlDoc = vd.format(pVALOR_DOCUMENTO_REAL);
                jValorDocumento.setText(vlDoc);
                jHistorico.setText(conecta.rs.getString("Historico"));
            } catch (Exception e) {
            }
            //
            ListarClientesDAO_CONSULTAS listaClientesDAO = new ListarClientesDAO_CONSULTAS();
            try {
                for (Clientes p : listaClientesDAO.read()) {
                    jComboBoxFornecedorCliente.addItem(p);
                }
            } catch (Exception ex) {
                Logger.getLogger(TelaConsultaContasPagasRecebidas.class.getName()).log(Level.SEVERE, null, ex);
            }
            Clientes clientes = (Clientes) jComboBoxFornecedorCliente.getSelectedItem();
            clientes.getIdForn();
            clientes.getRazaoSocial();
            objMov.setIdForn(clientes.getIdForn());
            //
            ListarBancosDAO_CR_CONSULTAS listaBancos = new ListarBancosDAO_CR_CONSULTAS();
            try {
                for (BancosContas b : listaBancos.read()) {
                    jComboBoxBanco.addItem(b);
                }
            } catch (Exception ex) {
                Logger.getLogger(TelaConsultaContasPagasRecebidas.class.getName()).log(Level.SEVERE, null, ex);
            }
            BancosContas banco = (BancosContas) jComboBoxBanco.getSelectedItem();
            banco.getIdBanco();
            banco.getContaCorrente();
            objMov.setIdBanco(banco.getIdBanco());
            jComboBoxContaCorrente.addItem(banco.getContaCorrente());
            //
            ListarFormaPagamentoDAO_CR_CONSULTAS listaForma = new ListarFormaPagamentoDAO_CR_CONSULTAS();
            try {
                for (FormaPagamento f : listaForma.read()) {
                    jComboBoxTipoPagamento.addItem(f);
                }
            } catch (Exception ex) {
                Logger.getLogger(TelaConsultaContasPagasRecebidas.class.getName()).log(Level.SEVERE, null, ex);
            }
            FormaPagamento forma = (FormaPagamento) jComboBoxTipoPagamento.getSelectedItem();
            forma.getIdForma();
            forma.getDescricaoForma();
            objMov.setIdForma(forma.getIdForma());
            //
            ListaCentroCustoDAO_CR_CONSULTAS listaDAOCentro = new ListaCentroCustoDAO_CR_CONSULTAS();
            try {
                for (CentroCusto c : listaDAOCentro.read()) {
                    jComboBoxCentroCusto.addItem(c);
                }
            } catch (Exception ex) {
                Logger.getLogger(TelaConsultaContasPagasRecebidas.class.getName()).log(Level.SEVERE, null, ex);
            }
            CentroCusto centro = (CentroCusto) jComboBoxCentroCusto.getSelectedItem();
            centro.getIdCentro();
            centro.getDescricaoCentro();
            objMov.setIdCentro(centro.getIdCentro());
            //
            ListarTiposContasDAO_CR_CONSULTAS listarDAOContas = new ListarTiposContasDAO_CR_CONSULTAS();
            try {
                for (TipoConta t : listarDAOContas.read()) {
                    jComboBoxTipoDespesa.addItem(t);
                }
            } catch (Exception ex) {
                Logger.getLogger(TelaConsultaContasPagasRecebidas.class.getName()).log(Level.SEVERE, null, ex);
            }
            TipoConta tipo = (TipoConta) jComboBoxTipoDespesa.getSelectedItem();
            tipo.getIdConta();
            tipo.getDescricaoConta();
            objMov.setIdConta(tipo.getIdConta());
        }
    }
}
